def get_default_schedule_data():
    """
    공사 일정 기본 템플릿 데이터
    프로젝트 생성 시 자동으로 초기화되는 표준 공정표
    """
    return [
    {
        "id": "auto-1",
        "main_category": "1. 공사준비",
        "process": "공사준비",
        "sub_process": "공사준비",
        "work_type": "설계도서 검토, 하도급업체의 선정 및 가설공사",
        "operating_rate_type": "EARTH",
        "order": 1,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 0.0,
        "unit": "식",
        "working_days": 45.0,
        "calendar_days": 1.5
    },
    {
        "id": "auto-2",
        "main_category": "1. 공사준비",
        "process": "공통가설",
        "sub_process": "공통가설",
        "work_type": "조립식가설사무소",
        "operating_rate_type": "EARTH",
        "order": 2,
        "quantity": 558.0,
        "productivity": 2.7,
        "crew_size": 1.0,
        "unit": "M2",
        "working_days": 206.66666666666666,
        "calendar_days": 300.38759689922483
    },
    {
        "id": "auto-3",
        "main_category": "1. 공사준비",
        "process": "공통가설",
        "sub_process": "공통가설",
        "work_type": "조립식가설울타리/E.G.I철판",
        "operating_rate_type": "EARTH",
        "order": 3,
        "quantity": 295.0,
        "productivity": 28.0,
        "crew_size": 1.0,
        "unit": "M",
        "working_days": 10.535714285714286,
        "calendar_days": 15.313538205980068
    },
    {
        "id": "auto-4",
        "main_category": "2. 토공사",
        "process": "철거",
        "sub_process": "철거",
        "work_type": "무근콘크리트깨기",
        "operating_rate_type": "EARTH",
        "order": 4,
        "quantity": 46.0,
        "productivity": 47.2,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 0.9745762711864406,
        "calendar_days": 60.0
    },
    {
        "id": "auto-5",
        "main_category": "2. 토공사",
        "process": "철거",
        "sub_process": "철거",
        "work_type": "철근콘크리트깨기",
        "operating_rate_type": "EARTH",
        "order": 5,
        "quantity": 45.0,
        "productivity": 26.4,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 1.7045454545454546,
        "calendar_days": 0.0
    },
    {
        "id": "auto-6",
        "main_category": "2. 토공사",
        "process": "철거",
        "sub_process": "철거",
        "work_type": "아스팔트포장깨기",
        "operating_rate_type": "EARTH",
        "order": 6,
        "quantity": 145.0,
        "productivity": 128.0,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 1.1328125,
        "calendar_days": 0.0
    },
    {
        "id": "auto-7",
        "main_category": "2. 토공사",
        "process": "철거",
        "sub_process": "철거",
        "work_type": "기계터파기/보통토사",
        "operating_rate_type": "EARTH",
        "order": 7,
        "quantity": 603.0,
        "productivity": 560.0,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 1.0767857142857142,
        "calendar_days": 0.0
    },
    {
        "id": "auto-8",
        "main_category": "2. 토공사",
        "process": "철거",
        "sub_process": "철거",
        "work_type": "되메우기/토사(소형장비)",
        "operating_rate_type": "EARTH",
        "order": 8,
        "quantity": 431.0,
        "productivity": 110.0,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 3.918181818181818,
        "calendar_days": 0.0
    },
    {
        "id": "auto-9",
        "main_category": "2. 토공사",
        "process": "토공",
        "sub_process": "흙막이가시설",
        "work_type": "강널말뚝(쉬트파일) 항발(전동식)",
        "operating_rate_type": "EARTH",
        "order": 9,
        "quantity": 524.0,
        "productivity": 28.55,
        "crew_size": 1.0,
        "unit": "본",
        "working_days": 18.353765323992995,
        "calendar_days": 26.67698448254796
    },
    {
        "id": "auto-10",
        "main_category": "2. 토공사",
        "process": "토공",
        "sub_process": "흙막이가시설",
        "work_type": "H파일 천공 후 근입(굴착식)",
        "operating_rate_type": "EARTH",
        "order": 10,
        "quantity": 43.0,
        "productivity": 21.5644820295983,
        "crew_size": 1.0,
        "unit": "본",
        "working_days": 1.9940196078431383,
        "calendar_days": 2.8982843137254917
    },
    {
        "id": "auto-11",
        "main_category": "2. 토공사",
        "process": "토공",
        "sub_process": "흙막이가시설",
        "work_type": "버팀보 설치(9~11M이하)",
        "operating_rate_type": "EARTH",
        "order": 11,
        "quantity": 235.0,
        "productivity": 8.247422680412372,
        "crew_size": 2.0,
        "unit": "본",
        "working_days": 14.246875,
        "calendar_days": 20.70766715116279
    },
    {
        "id": "auto-12",
        "main_category": "2. 토공사",
        "process": "토공",
        "sub_process": "터파기",
        "work_type": "구조물터파기(토사)",
        "operating_rate_type": "EARTH",
        "order": 12,
        "quantity": 1843.5,
        "productivity": 560.0,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 3.2919642857142857,
        "calendar_days": 4.784831810631229
    },
    {
        "id": "auto-13",
        "main_category": "2. 토공사",
        "process": "토공",
        "sub_process": "터파기",
        "work_type": "구조물터파기(토사)",
        "operating_rate_type": "EARTH",
        "order": 13,
        "quantity": 5530.5,
        "productivity": 288.47,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 19.1718376260963,
        "calendar_days": 27.86604306118648
    },
    {
        "id": "auto-14",
        "main_category": "2. 토공사",
        "process": "토공",
        "sub_process": "터파기",
        "work_type": "되메우기/토사(백호90%+인력10%)",
        "operating_rate_type": "EARTH",
        "order": 14,
        "quantity": 484.0,
        "productivity": 110.0,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 4.4,
        "calendar_days": 6.395348837209303
    },
    {
        "id": "auto-15",
        "main_category": "2. 토공사",
        "process": "토공",
        "sub_process": "지정공사",
        "work_type": "콘크리트파일",
        "operating_rate_type": "EARTH",
        "order": 15,
        "quantity": 147.0,
        "productivity": 21.5644820295983,
        "crew_size": 1.0,
        "unit": "본",
        "working_days": 6.816764705882356,
        "calendar_days": 9.908088235294123
    },
    {
        "id": "auto-16",
        "main_category": "2. 토공사",
        "process": "토공",
        "sub_process": "지정공사",
        "work_type": "말뚝두부정리(콘크리트)",
        "operating_rate_type": "EARTH",
        "order": 16,
        "quantity": 147.0,
        "productivity": 9.25925925925926,
        "crew_size": 3.0,
        "unit": "본",
        "working_days": 5.292,
        "calendar_days": 7.69186046511628
    },
    {
        "id": "auto-17",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "기초공사",
        "work_type": "버림콘크리트(25-18-80)",
        "operating_rate_type": "FRAME",
        "order": 17,
        "quantity": 72.6,
        "productivity": 189.0,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 0.3841269841269841,
        "calendar_days": 30.39504858518767
    },
    {
        "id": "auto-18",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "기초공사",
        "work_type": "철근 현장가공 및 조립",
        "operating_rate_type": "FRAME",
        "order": 18,
        "quantity": 31.101,
        "productivity": 4.0,
        "crew_size": 2.0,
        "unit": "TON",
        "working_days": 3.887625,
        "calendar_days": 0.0
    },
    {
        "id": "auto-19",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "기초공사",
        "work_type": "유로폼",
        "operating_rate_type": "FRAME",
        "order": 19,
        "quantity": 611.98,
        "productivity": 35.0,
        "crew_size": 2.0,
        "unit": "M2",
        "working_days": 8.742571428571429,
        "calendar_days": 0.0
    },
    {
        "id": "auto-20",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "기초공사",
        "work_type": "콘크리트 펌프차 타설(철근)",
        "operating_rate_type": "FRAME",
        "order": 20,
        "quantity": 1319.93,
        "productivity": 189.0,
        "crew_size": 2.0,
        "unit": "M3",
        "working_days": 3.491878306878307,
        "calendar_days": 0.0
    },
    {
        "id": "auto-21",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "기초공사",
        "work_type": "양생",
        "operating_rate_type": "FRAME",
        "order": 21,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 0.0,
        "unit": "",
        "working_days": 3.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-22",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지하1층",
        "work_type": "철근 현장가공 및 조립",
        "operating_rate_type": "FRAME",
        "order": 22,
        "quantity": 75.866,
        "productivity": 4.0,
        "crew_size": 3.0,
        "unit": "TON",
        "working_days": 6.322166666666667,
        "calendar_days": 55.35984875196402
    },
    {
        "id": "auto-23",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지하1층",
        "work_type": "유로폼, 합판, 경사 등",
        "operating_rate_type": "FRAME",
        "order": 23,
        "quantity": 2846.04,
        "productivity": 35.0,
        "crew_size": 6.0,
        "unit": "M2",
        "working_days": 13.552571428571428,
        "calendar_days": 0.0
    },
    {
        "id": "auto-24",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지하1층",
        "work_type": "데크플레이트",
        "operating_rate_type": "FRAME",
        "order": 24,
        "quantity": 1083.31,
        "productivity": 20.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 10.8331,
        "calendar_days": 0.0
    },
    {
        "id": "auto-25",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지하1층",
        "work_type": "콘크리트 펌프차 타설(철근)",
        "operating_rate_type": "FRAME",
        "order": 25,
        "quantity": 883.584,
        "productivity": 156.0,
        "crew_size": 2.0,
        "unit": "M3",
        "working_days": 2.832,
        "calendar_days": 0.0
    },
    {
        "id": "auto-26",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지하1층",
        "work_type": "양생",
        "operating_rate_type": "FRAME",
        "order": 26,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 1.0,
        "unit": "",
        "working_days": 1.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-27",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상1층",
        "work_type": "철근 현장가공 및 조립",
        "operating_rate_type": "FRAME",
        "order": 27,
        "quantity": 44.630900000000004,
        "productivity": 4.0,
        "crew_size": 3.0,
        "unit": "TON",
        "working_days": 3.719241666666667,
        "calendar_days": 41.60934534135955
    },
    {
        "id": "auto-28",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상1층",
        "work_type": "유로폼, 합판, 경사 등",
        "operating_rate_type": "FRAME",
        "order": 28,
        "quantity": 1860.89,
        "productivity": 35.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 10.633657142857144,
        "calendar_days": 0.0
    },
    {
        "id": "auto-29",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상1층",
        "work_type": "데크플레이트",
        "operating_rate_type": "FRAME",
        "order": 29,
        "quantity": 911.55,
        "productivity": 20.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 9.115499999999999,
        "calendar_days": 0.0
    },
    {
        "id": "auto-30",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상1층",
        "work_type": "콘크리트 펌프차 타설(철근)",
        "operating_rate_type": "FRAME",
        "order": 30,
        "quantity": 521.824,
        "productivity": 156.0,
        "crew_size": 2.0,
        "unit": "M3",
        "working_days": 1.6725128205128204,
        "calendar_days": 0.0
    },
    {
        "id": "auto-31",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상1층",
        "work_type": "양생",
        "operating_rate_type": "FRAME",
        "order": 31,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 1.0,
        "unit": "",
        "working_days": 1.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-32",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상2층",
        "work_type": "철근 현장가공 및 조립",
        "operating_rate_type": "FRAME",
        "order": 32,
        "quantity": 40.8411,
        "productivity": 4.0,
        "crew_size": 3.0,
        "unit": "TON",
        "working_days": 3.403425,
        "calendar_days": 34.78005084685843
    },
    {
        "id": "auto-33",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상2층",
        "work_type": "유로폼, 합판, 경사 등",
        "operating_rate_type": "FRAME",
        "order": 33,
        "quantity": 1787.0900000000001,
        "productivity": 35.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 10.211942857142859,
        "calendar_days": 0.0
    },
    {
        "id": "auto-34",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상2층",
        "work_type": "데크플레이트",
        "operating_rate_type": "FRAME",
        "order": 34,
        "quantity": 1163.3,
        "productivity": 20.0,
        "crew_size": 10.0,
        "unit": "M2",
        "working_days": 5.8165,
        "calendar_days": 0.0
    },
    {
        "id": "auto-35",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상2층",
        "work_type": "콘크리트 펌프차 타설(철근)",
        "operating_rate_type": "FRAME",
        "order": 35,
        "quantity": 457.583,
        "productivity": 156.0,
        "crew_size": 2.0,
        "unit": "M3",
        "working_days": 1.4666121794871796,
        "calendar_days": 0.0
    },
    {
        "id": "auto-36",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상2층",
        "work_type": "양생",
        "operating_rate_type": "FRAME",
        "order": 36,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 1.0,
        "unit": "",
        "working_days": 1.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-37",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상3층",
        "work_type": "철근 현장가공 및 조립",
        "operating_rate_type": "FRAME",
        "order": 37,
        "quantity": 38.6946,
        "productivity": 4.0,
        "crew_size": 3.0,
        "unit": "TON",
        "working_days": 3.2245500000000002,
        "calendar_days": 40.18102457211922
    },
    {
        "id": "auto-38",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상3층",
        "work_type": "유로폼, 합판, 경사 등",
        "operating_rate_type": "FRAME",
        "order": 38,
        "quantity": 1765.8799999999999,
        "productivity": 35.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 10.090742857142857,
        "calendar_days": 0.0
    },
    {
        "id": "auto-39",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상3층",
        "work_type": "데크플레이트",
        "operating_rate_type": "FRAME",
        "order": 39,
        "quantity": 967.4799999999999,
        "productivity": 20.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 9.6748,
        "calendar_days": 0.0
    },
    {
        "id": "auto-40",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상3층",
        "work_type": "콘크리트 펌프차 타설(철근)",
        "operating_rate_type": "FRAME",
        "order": 40,
        "quantity": 412.612,
        "productivity": 156.0,
        "crew_size": 2.0,
        "unit": "M3",
        "working_days": 1.322474358974359,
        "calendar_days": 0.0
    },
    {
        "id": "auto-41",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "지상3층",
        "work_type": "양생",
        "operating_rate_type": "FRAME",
        "order": 41,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 1.0,
        "unit": "",
        "working_days": 1.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-42",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "PH1",
        "work_type": "철근 현장가공 및 조립",
        "operating_rate_type": "FRAME",
        "order": 42,
        "quantity": 12.6634,
        "productivity": 4.0,
        "crew_size": 2.0,
        "unit": "TON",
        "working_days": 1.582925,
        "calendar_days": 21.614131089931572
    },
    {
        "id": "auto-43",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "PH1",
        "work_type": "유로폼, 합판, 경사 등",
        "operating_rate_type": "FRAME",
        "order": 43,
        "quantity": 1082.17,
        "productivity": 35.0,
        "crew_size": 3.0,
        "unit": "M2",
        "working_days": 10.306380952380954,
        "calendar_days": 0.0
    },
    {
        "id": "auto-44",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "PH1",
        "work_type": "콘크리트 펌프차 타설(철근)",
        "operating_rate_type": "FRAME",
        "order": 44,
        "quantity": 135.55,
        "productivity": 156.0,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 0.8689102564102564,
        "calendar_days": 0.0
    },
    {
        "id": "auto-45",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "PH1",
        "work_type": "양생",
        "operating_rate_type": "FRAME",
        "order": 45,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 1.0,
        "unit": "",
        "working_days": 1.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-46",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "PH2",
        "work_type": "철근 현장가공 및 조립",
        "operating_rate_type": "FRAME",
        "order": 46,
        "quantity": 0.7039,
        "productivity": 4.0,
        "crew_size": 1.0,
        "unit": "TON",
        "working_days": 0.175975,
        "calendar_days": 3.308233603165562
    },
    {
        "id": "auto-47",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "PH2",
        "work_type": "유로폼, 합판, 경사 등",
        "operating_rate_type": "FRAME",
        "order": 47,
        "quantity": 43.62,
        "productivity": 35.0,
        "crew_size": 1.0,
        "unit": "M2",
        "working_days": 1.2462857142857142,
        "calendar_days": 0.0
    },
    {
        "id": "auto-48",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "PH2",
        "work_type": "콘크리트 펌프차 타설(철근)",
        "operating_rate_type": "FRAME",
        "order": 48,
        "quantity": 3.272,
        "productivity": 156.0,
        "crew_size": 1.0,
        "unit": "M3",
        "working_days": 0.020974358974358974,
        "calendar_days": 0.0
    },
    {
        "id": "auto-49",
        "main_category": "3. 골조공사",
        "process": "RC공사",
        "sub_process": "PH2",
        "work_type": "양생",
        "operating_rate_type": "FRAME",
        "order": 49,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 1.0,
        "unit": "",
        "working_days": 1.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-50",
        "main_category": "3. 골조공사",
        "process": "철골공사",
        "sub_process": "장식벽",
        "work_type": "철골세우기",
        "operating_rate_type": "FRAME",
        "order": 50,
        "quantity": 31.142,
        "productivity": 15.0,
        "crew_size": 1.0,
        "unit": "TON",
        "working_days": 2.0761333333333334,
        "calendar_days": 3.311217437533227
    },
    {
        "id": "auto-51",
        "main_category": "4. 마감공사",
        "process": "외부마감",
        "sub_process": "석재패널",
        "work_type": "석재단열패널(마천석)/관급",
        "operating_rate_type": "EXT_FIN",
        "order": 51,
        "quantity": 289.0,
        "productivity": 2.44,
        "crew_size": 6.0,
        "unit": "M2",
        "working_days": 19.740437158469945,
        "calendar_days": 31.48395081095685
    },
    {
        "id": "auto-52",
        "main_category": "4. 마감공사",
        "process": "외부마감",
        "sub_process": "외장공사",
        "work_type": "AL복합패널(틀포함)/자재관급",
        "operating_rate_type": "EXT_FIN",
        "order": 52,
        "quantity": 3427.0,
        "productivity": 15.9,
        "crew_size": 9.0,
        "unit": "M2",
        "working_days": 23.94828791055206,
        "calendar_days": 38.19503653995544
    },
    {
        "id": "auto-53",
        "main_category": "4. 마감공사",
        "process": "외부마감",
        "sub_process": "창호공사",
        "work_type": "AGD 창호",
        "operating_rate_type": "EXT_FIN",
        "order": 53,
        "quantity": 189.0,
        "productivity": 6.94,
        "crew_size": 1.0,
        "unit": "M2",
        "working_days": 27.233429394812678,
        "calendar_days": 43.434496642444465
    },
    {
        "id": "auto-54",
        "main_category": "4. 마감공사",
        "process": "외부마감",
        "sub_process": "유리공사",
        "work_type": "칼라로이복층유리(일면반강화)",
        "operating_rate_type": "EXT_FIN",
        "order": 54,
        "quantity": 859.0,
        "productivity": 5.91715976331361,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 29.034199999999995,
        "calendar_days": 46.30653907496012
    },
    {
        "id": "auto-55",
        "main_category": "4. 마감공사",
        "process": "내부마감",
        "sub_process": "조적공사",
        "work_type": "8인치 블록/H:3.6이하.양면마감",
        "operating_rate_type": "INT_FIN",
        "order": 55,
        "quantity": 1110.0,
        "productivity": 17.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 13.058823529411764,
        "calendar_days": 18.980848153214776
    },
    {
        "id": "auto-56",
        "main_category": "4. 마감공사",
        "process": "내부마감",
        "sub_process": "석공사",
        "work_type": "화강석붙임(습식, 혼드)",
        "operating_rate_type": "INT_FIN",
        "order": 56,
        "quantity": 82.0,
        "productivity": 2.2222222222222223,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 7.38,
        "calendar_days": 10.726744186046512
    },
    {
        "id": "auto-57",
        "main_category": "4. 마감공사",
        "process": "내부마감",
        "sub_process": "타일공사",
        "work_type": "도기질타일접착제붙임/타일관급",
        "operating_rate_type": "INT_FIN",
        "order": 57,
        "quantity": 915.0,
        "productivity": 26.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 7.038461538461538,
        "calendar_days": 10.230322003577818
    },
    {
        "id": "auto-58",
        "main_category": "4. 마감공사",
        "process": "내부마감",
        "sub_process": "방수공사",
        "work_type": "복합방수",
        "operating_rate_type": "INT_FIN",
        "order": 58,
        "quantity": 1986.0,
        "productivity": 31.25,
        "crew_size": 4.0,
        "unit": "M2",
        "working_days": 15.888,
        "calendar_days": 23.093023255813954
    },
    {
        "id": "auto-59",
        "main_category": "4. 마감공사",
        "process": "내부마감",
        "sub_process": "미장공사",
        "work_type": "모르타르 바름",
        "operating_rate_type": "INT_FIN",
        "order": 59,
        "quantity": 1399.0,
        "productivity": 29.0,
        "crew_size": 4.0,
        "unit": "M2",
        "working_days": 12.060344827586206,
        "calendar_days": 17.52957097032879
    },
    {
        "id": "auto-60",
        "main_category": "4. 마감공사",
        "process": "내부마감",
        "sub_process": "금속공사",
        "work_type": "내진천장틀(T-BAR)/1.0m이상",
        "operating_rate_type": "INT_FIN",
        "order": 60,
        "quantity": 1881.0,
        "productivity": 60.0,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 6.27,
        "calendar_days": 9.113372093023257
    },
    {
        "id": "auto-61",
        "main_category": "4. 마감공사",
        "process": "내부마감",
        "sub_process": "수장공사",
        "work_type": "비닐시트",
        "operating_rate_type": "INT_FIN",
        "order": 61,
        "quantity": 1271.0,
        "productivity": 18.518518518518515,
        "crew_size": 5.0,
        "unit": "M2",
        "working_days": 13.726800000000003,
        "calendar_days": 19.95174418604652
    },
    {
        "id": "auto-62",
        "main_category": "4. 마감공사",
        "process": "내부마감",
        "sub_process": "도장공사",
        "work_type": "친환경수성페인트(롤러칠)/GB면",
        "operating_rate_type": "INT_FIN",
        "order": 62,
        "quantity": 2739.0,
        "productivity": 583.3333333333334,
        "crew_size": 1.0,
        "unit": "M2",
        "working_days": 4.695428571428571,
        "calendar_days": 6.824750830564784
    },
    {
        "id": "auto-63",
        "main_category": "5. 기계, 전기, 소방, 통신",
        "process": "MEP",
        "sub_process": "시운전",
        "work_type": "수전, T.A.B Commissioning",
        "operating_rate_type": "INT_FIN",
        "order": 63,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 0.0,
        "unit": "식",
        "working_days": 0.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-64",
        "main_category": "6. 부대토목 및 조경",
        "process": "우수공사",
        "sub_process": "우수공사",
        "work_type": "흄관접합및부설",
        "operating_rate_type": "EARTH",
        "order": 64,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 0.0,
        "unit": "M",
        "working_days": 0.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-65",
        "main_category": "6. 부대토목 및 조경",
        "process": "오수공사",
        "sub_process": "오수공사",
        "work_type": "오수맨홀",
        "operating_rate_type": "EARTH",
        "order": 65,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 0.0,
        "unit": "개소",
        "working_days": 0.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-66",
        "main_category": "6. 부대토목 및 조경",
        "process": "포장공사",
        "sub_process": "포장공사",
        "work_type": "보도포장",
        "operating_rate_type": "EARTH",
        "order": 66,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 0.0,
        "unit": "M2",
        "working_days": 0.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-67",
        "main_category": "6. 부대토목 및 조경",
        "process": "조경",
        "sub_process": "조경 및 식재",
        "work_type": "인조화강석블록포장",
        "operating_rate_type": "EARTH",
        "order": 67,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 0.0,
        "unit": "M2",
        "working_days": 0.0,
        "calendar_days": 0.0
    },
    {
        "id": "auto-68",
        "main_category": "7. 정리기간",
        "process": "준공준비",
        "sub_process": "준공준비",
        "work_type": "발주처 준공 검사 및 품질향상",
        "operating_rate_type": "INT_FIN",
        "order": 68,
        "quantity": 0.0,
        "productivity": 0.0,
        "crew_size": 0.0,
        "unit": "",
        "working_days": 0.0,
        "calendar_days": 30.0
    }
]
