# Generated by Django 5.2.3 on 2025-10-13 04:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkScheduleWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EARTH", "토공사"),
                            ("FRAME", "골조공사"),
                            ("EXT_FIN", "외부 마감공사"),
                            ("INT_FIN", "내부 마감공사"),
                            ("POUR", "골조 타설"),
                        ],
                        help_text="공종 타입",
                        max_length=16,
                    ),
                ),
                (
                    "pct_7d",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="주7일 작업 시 적용 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="주7일(%)",
                    ),
                ),
                (
                    "pct_6d",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="주6일 작업 시 적용 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="주6일(%)",
                    ),
                ),
                (
                    "pct_5d",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="주5일 작업 시 적용 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="주5일(%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="소유 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedule_weights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "공종별 주간 가중치",
                "verbose_name_plural": "공종별 주간 가중치",
                "indexes": [
                    models.Index(fields=["user", "type"], name="idx_user_type")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "type"), name="uniq_user_type"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("pct_7d__gte", 0), ("pct_7d__lte", 100)),
                        name="pct_7d_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("pct_6d__gte", 0), ("pct_6d__lte", 100)),
                        name="pct_6d_0_100",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("pct_5d__gte", 0), ("pct_5d__lte", 100)),
                        name="pct_5d_0_100",
                    ),
                ],
            },
        ),
    ]
