# Generated by Django 5.2.5 on 2025-10-14 06:46

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConstructionOverview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("민간공사", "민간공사"), ("공공공사", "공공공사")],
                        default="민간공사",
                        max_length=50,
                        verbose_name="발주처",
                    ),
                ),
                (
                    "building_use",
                    models.CharField(
                        choices=[
                            ("공동주택", "공동주택"),
                            ("오피스텔", "오피스텔"),
                            ("상업시설", "상업시설"),
                            ("기타", "기타"),
                        ],
                        default="공동주택",
                        max_length=50,
                        verbose_name="건물 용도",
                    ),
                ),
                (
                    "construction_type",
                    models.CharField(
                        choices=[
                            ("턴키", "턴키"),
                            ("CM", "CM"),
                            ("시공", "시공"),
                            ("기타", "기타"),
                        ],
                        default="턴키",
                        max_length=50,
                        verbose_name="공사 형식",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="위치"
                    ),
                ),
                (
                    "site_area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="대지면적(㎡)",
                    ),
                ),
                (
                    "adjacent_road",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="인접도로"
                    ),
                ),
                (
                    "adjacent_side_count",
                    models.PositiveIntegerField(default=0, verbose_name="도로 접한 면 수"),
                ),
                (
                    "elevation_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="최고 고저차(m)",
                    ),
                ),
                (
                    "elevation_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="최저 고저차(m)",
                    ),
                ),
                (
                    "nearby_env",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("학교", "학교"),
                            ("주거지", "주거지"),
                            ("노후시설", "노후시설"),
                            ("문화재", "문화재"),
                            ("택지개발", "택지개발"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="주변현황",
                    ),
                ),
                (
                    "basement_floors",
                    models.PositiveIntegerField(default=10, verbose_name="지하층수"),
                ),
                (
                    "ground_floors",
                    models.PositiveIntegerField(default=10, verbose_name="지상층수"),
                ),
                (
                    "total_units",
                    models.PositiveIntegerField(default=0, verbose_name="세대수"),
                ),
                (
                    "total_buildings",
                    models.PositiveIntegerField(default=0, verbose_name="동수"),
                ),
                (
                    "total_floor_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="연면적(㎡)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Earthwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support_earth_anchor",
                    models.PositiveIntegerField(default=25, verbose_name="어스앵커(소요일)"),
                ),
                (
                    "support_raker",
                    models.PositiveIntegerField(default=25, verbose_name="레이커(소요일)"),
                ),
                (
                    "support_strut",
                    models.PositiveIntegerField(default=30, verbose_name="스트럿(소요일)"),
                ),
                (
                    "production_cip",
                    models.DecimalField(
                        decimal_places=1, default=81.4, max_digits=6, verbose_name="CIP"
                    ),
                ),
                (
                    "production_slurry",
                    models.DecimalField(
                        decimal_places=1,
                        default=55.0,
                        max_digits=6,
                        verbose_name="Slurry Wall",
                    ),
                ),
                (
                    "production_sheet",
                    models.DecimalField(
                        decimal_places=1,
                        default=150.0,
                        max_digits=6,
                        verbose_name="Sheet Pile",
                    ),
                ),
                (
                    "production_dwall",
                    models.DecimalField(
                        decimal_places=1,
                        default=60.0,
                        max_digits=6,
                        verbose_name="D-WALL",
                    ),
                ),
                (
                    "production_hpile",
                    models.DecimalField(
                        decimal_places=1,
                        default=81.4,
                        max_digits=6,
                        verbose_name="H-PILE+토류판",
                    ),
                ),
                (
                    "cip_soil",
                    models.DecimalField(
                        decimal_places=1,
                        default=100.0,
                        max_digits=6,
                        verbose_name="CIP-토사(m/일)",
                    ),
                ),
                (
                    "cip_weathered",
                    models.DecimalField(
                        decimal_places=1,
                        default=80.0,
                        max_digits=6,
                        verbose_name="CIP-풍화암(m/일)",
                    ),
                ),
                (
                    "cip_soft_rock",
                    models.DecimalField(
                        decimal_places=1,
                        default=60.0,
                        max_digits=6,
                        verbose_name="CIP-연암(m/일)",
                    ),
                ),
                (
                    "cip_hard_rock",
                    models.DecimalField(
                        decimal_places=1,
                        default=60.0,
                        max_digits=6,
                        verbose_name="CIP-경암(m/일)",
                    ),
                ),
                (
                    "hpile_soil",
                    models.DecimalField(
                        decimal_places=1,
                        default=100.0,
                        max_digits=6,
                        verbose_name="H-Pile-토사(m/일)",
                    ),
                ),
                (
                    "hpile_weathered",
                    models.DecimalField(
                        decimal_places=1,
                        default=80.0,
                        max_digits=6,
                        verbose_name="H-Pile-풍화암(m/일)",
                    ),
                ),
                (
                    "hpile_soft_rock",
                    models.DecimalField(
                        decimal_places=1,
                        default=60.0,
                        max_digits=6,
                        verbose_name="H-Pile-연암(m/일)",
                    ),
                ),
                (
                    "hpile_hard_rock",
                    models.DecimalField(
                        decimal_places=1,
                        default=60.0,
                        max_digits=6,
                        verbose_name="H-Pile-경암(m/일)",
                    ),
                ),
                (
                    "surcharge_school",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=4,
                        verbose_name="학교 주변 할증(%)",
                    ),
                ),
                (
                    "surcharge_residential",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=4,
                        verbose_name="주거지 주변 할증(%)",
                    ),
                ),
                (
                    "surcharge_old_facility",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=4,
                        verbose_name="노후시설 주변 할증(%)",
                    ),
                ),
                (
                    "surcharge_cultural",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=4,
                        verbose_name="문화재 주변 할증(%)",
                    ),
                ),
                (
                    "surcharge_development",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.0,
                        max_digits=4,
                        verbose_name="택지개발 주변 할증(%)",
                    ),
                ),
                (
                    "excavation_soil",
                    models.DecimalField(
                        decimal_places=0,
                        default=600,
                        max_digits=6,
                        verbose_name="토사 생산량(㎥/일)",
                    ),
                ),
                (
                    "excavation_weathered",
                    models.DecimalField(
                        decimal_places=0,
                        default=420,
                        max_digits=6,
                        verbose_name="풍화암 생산량(㎥/일)",
                    ),
                ),
                (
                    "haul_direct",
                    models.DecimalField(
                        decimal_places=1, default=1.0, max_digits=3, verbose_name="직상차"
                    ),
                ),
                (
                    "haul_cram",
                    models.DecimalField(
                        decimal_places=1, default=1.5, max_digits=3, verbose_name="크람쉘"
                    ),
                ),
                (
                    "blasting_soft_vibrationless",
                    models.DecimalField(
                        decimal_places=0,
                        default=120,
                        max_digits=6,
                        verbose_name="연암-미진동(㎥/일)",
                    ),
                ),
                (
                    "blasting_soft_precision",
                    models.DecimalField(
                        decimal_places=0,
                        default=160,
                        max_digits=6,
                        verbose_name="연암-정밀제어(㎥/일)",
                    ),
                ),
                (
                    "blasting_soft_small",
                    models.DecimalField(
                        decimal_places=0,
                        default=300,
                        max_digits=6,
                        verbose_name="연암-소규모(㎥/일)",
                    ),
                ),
                (
                    "blasting_soft_medium",
                    models.DecimalField(
                        decimal_places=0,
                        default=450,
                        max_digits=6,
                        verbose_name="연암-중규모(㎥/일)",
                    ),
                ),
                (
                    "blasting_hard_vibrationless",
                    models.DecimalField(
                        decimal_places=0,
                        default=60,
                        max_digits=6,
                        verbose_name="경암-미진동(㎥/일)",
                    ),
                ),
                (
                    "blasting_hard_precision",
                    models.DecimalField(
                        decimal_places=0,
                        default=100,
                        max_digits=6,
                        verbose_name="경암-정밀제어(㎥/일)",
                    ),
                ),
                (
                    "blasting_hard_small",
                    models.DecimalField(
                        decimal_places=0,
                        default=200,
                        max_digits=6,
                        verbose_name="경암-소규모(㎥/일)",
                    ),
                ),
                (
                    "blasting_hard_medium",
                    models.DecimalField(
                        decimal_places=0,
                        default=350,
                        max_digits=6,
                        verbose_name="경암-중규모(㎥/일)",
                    ),
                ),
                (
                    "rcd_1500",
                    models.DecimalField(
                        decimal_places=0,
                        default=10,
                        max_digits=6,
                        verbose_name="RCD-1500mm",
                    ),
                ),
                (
                    "rcd_1800",
                    models.DecimalField(
                        decimal_places=0,
                        default=20,
                        max_digits=6,
                        verbose_name="RCD-1800mm",
                    ),
                ),
                (
                    "rcd_2000",
                    models.DecimalField(
                        decimal_places=0,
                        default=30,
                        max_digits=6,
                        verbose_name="RCD-2000mm",
                    ),
                ),
                (
                    "rcd_2500",
                    models.DecimalField(
                        decimal_places=0,
                        default=40,
                        max_digits=6,
                        verbose_name="RCD-2500mm",
                    ),
                ),
                (
                    "rcd_3000",
                    models.DecimalField(
                        decimal_places=0,
                        default=50,
                        max_digits=6,
                        verbose_name="RCD-3000mm",
                    ),
                ),
                (
                    "prd_600",
                    models.DecimalField(
                        decimal_places=0,
                        default=10,
                        max_digits=6,
                        verbose_name="PRD-600mm",
                    ),
                ),
                (
                    "prd_750",
                    models.DecimalField(
                        decimal_places=0,
                        default=20,
                        max_digits=6,
                        verbose_name="PRD-750mm",
                    ),
                ),
                (
                    "prd_900",
                    models.DecimalField(
                        decimal_places=0,
                        default=30,
                        max_digits=6,
                        verbose_name="PRD-900mm",
                    ),
                ),
                (
                    "prd_1000",
                    models.DecimalField(
                        decimal_places=0,
                        default=40,
                        max_digits=6,
                        verbose_name="PRD-1000mm",
                    ),
                ),
                (
                    "prd_1500",
                    models.DecimalField(
                        decimal_places=0,
                        default=50,
                        max_digits=6,
                        verbose_name="PRD-1500mm",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="EarthworkInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sunta", models.BooleanField(default=True)),
                (
                    "reverse_excavation_months",
                    models.CharField(
                        choices=[
                            ("Down-Up", "Down-Up"),
                            ("Up-Up", "Up-Up"),
                            ("Semi Top Down", "Semi Top Down"),
                            ("D-WALL", "D-WALL"),
                            ("Top-Down", "Top-Down"),
                        ],
                        default="Top-Down",
                        max_length=50,
                        verbose_name="역타 공법",
                    ),
                ),
                (
                    "earth_retention_method",
                    models.CharField(
                        choices=[
                            ("CIP", "CIP"),
                            ("Slurry Wall", "Slurry Wall"),
                            ("Sheet Pile", "Sheet Pile"),
                            ("D-WALL", "D-WALL"),
                            ("H-PILE+토류판", "H-PILE+토류판"),
                        ],
                        default="CIP",
                        max_length=50,
                        verbose_name="흙막이 공법",
                    ),
                ),
                (
                    "retention_perimeter_length",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=8,
                        verbose_name="외곽 길이(m)",
                    ),
                ),
                (
                    "drilling_depth",
                    models.DecimalField(
                        decimal_places=1,
                        default=10,
                        max_digits=5,
                        verbose_name="천공 심도(m)",
                    ),
                ),
                (
                    "crew_count",
                    models.PositiveIntegerField(default=2, verbose_name="투입 조(장비)"),
                ),
                ("is_special_retention", models.BooleanField(default=True)),
                (
                    "special_retention_extra_days",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="특수 흙막이 추가 작업일수"
                    ),
                ),
                (
                    "support_method",
                    models.CharField(
                        choices=[("레이커", "레이커"), ("어스앵커", "어스앵커"), ("스트럿", "스트럿")],
                        default="어스앵커",
                        max_length=50,
                        verbose_name="지보공 공법",
                    ),
                ),
                (
                    "total_earth_volume",
                    models.DecimalField(
                        decimal_places=1,
                        default=10000,
                        max_digits=10,
                        verbose_name="전체 토사량(㎥)",
                    ),
                ),
                (
                    "soil_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="토사 비율(%)",
                    ),
                ),
                (
                    "weathered_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=25,
                        max_digits=5,
                        verbose_name="풍화암 비율(%)",
                    ),
                ),
                (
                    "soft_rock_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=15,
                        max_digits=5,
                        verbose_name="연암 비율(%)",
                    ),
                ),
                (
                    "hard_rock_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=5,
                        verbose_name="경암 비율(%)",
                    ),
                ),
                (
                    "soil_excavation_method",
                    models.CharField(
                        default="직상차", max_length=20, verbose_name="토사 반출방법"
                    ),
                ),
                (
                    "soil_direct_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="직상차 비율(%)",
                    ),
                ),
                (
                    "soil_cram_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="크람쉘 비율(%)",
                    ),
                ),
                (
                    "soil_crew_actual",
                    models.PositiveIntegerField(default=2, verbose_name="토사 실제 투입조"),
                ),
                (
                    "weathered_direct_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="풍화암 직상차 비율(%)",
                    ),
                ),
                (
                    "weathered_cram_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=50,
                        max_digits=5,
                        verbose_name="풍화암 크람쉘 비율(%)",
                    ),
                ),
                (
                    "weathered_crew_actual",
                    models.PositiveIntegerField(default=3, verbose_name="풍화암 실제 투입조"),
                ),
                (
                    "softrock_vibration_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=70,
                        max_digits=5,
                        verbose_name="연암 미진동 비율(%)",
                    ),
                ),
                (
                    "softrock_precision_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=15,
                        max_digits=5,
                        verbose_name="연암 정밀제어 비율(%)",
                    ),
                ),
                (
                    "softrock_small_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=5,
                        verbose_name="연암 소규모 비율(%)",
                    ),
                ),
                (
                    "softrock_medium_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=5,
                        verbose_name="연암 중규모 비율(%)",
                    ),
                ),
                (
                    "softrock_direct_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="연암 반출방법 직상차 비율(%)",
                    ),
                ),
                (
                    "softrock_cram_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="연암 반출방법 크람쉘(%)",
                    ),
                ),
                (
                    "softrock_crew_actual",
                    models.PositiveIntegerField(default=1, verbose_name="연암 실제 투입조"),
                ),
                (
                    "hardrock_vibration_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=70,
                        max_digits=5,
                        verbose_name="경암 미진동 비율(%)",
                    ),
                ),
                (
                    "hardrock_precision_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=15,
                        max_digits=5,
                        verbose_name="경암 정밀제어 비율(%)",
                    ),
                ),
                (
                    "hardrock_small_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=10,
                        max_digits=5,
                        verbose_name="경암 소규모 비율(%)",
                    ),
                ),
                (
                    "hardrock_medium_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        max_digits=5,
                        verbose_name="경암 중규모 비율(%)",
                    ),
                ),
                (
                    "hardrock_direct_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="경암 반출방법 직상차 비율(%)",
                    ),
                ),
                (
                    "hardrock_cram_ratio",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="경암 반출방법 크람쉘(%)",
                    ),
                ),
                (
                    "hardrock_crew_actual",
                    models.PositiveIntegerField(default=1, verbose_name="경암 실제 투입조"),
                ),
                (
                    "designated_method",
                    models.CharField(
                        choices=[
                            ("RCD", "RCD"),
                            ("PRD", "PRD"),
                            ("PHC-Pile", "PHC-Pile"),
                            ("지내력 기초", "지내력 기초"),
                        ],
                        default="RCD",
                        max_length=50,
                        verbose_name="지정 공법",
                    ),
                ),
                (
                    "designated_work_unit",
                    models.PositiveIntegerField(default=20, verbose_name="공수"),
                ),
                (
                    "designated_drilling_depth",
                    models.DecimalField(
                        decimal_places=1,
                        default=15.0,
                        max_digits=5,
                        verbose_name="천공 심도(m)",
                    ),
                ),
                (
                    "designated_diameter",
                    models.DecimalField(
                        decimal_places=1,
                        default=1000.0,
                        max_digits=6,
                        verbose_name="RCD/PRD 직경(mm)",
                    ),
                ),
                (
                    "designated_crew",
                    models.PositiveIntegerField(default=1, verbose_name="투입 조(장비)"),
                ),
                ("is_surcharge", models.BooleanField(default=False)),
                (
                    "parallel_retention",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="병행률 - 흙막이가시설(%)",
                    ),
                ),
                (
                    "parallel_support",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="병행률 - 지보공(%)",
                    ),
                ),
                (
                    "parallel_excavation",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="병행률 - 터파기(%)",
                    ),
                ),
                (
                    "parallel_designated",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        max_digits=5,
                        verbose_name="병행률 - 지정공사(%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "토공사 입력",
                "verbose_name_plural": "토공사 입력 목록",
            },
        ),
        migrations.CreateModel(
            name="FrameWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_thickness_data",
                    models.JSONField(
                        default=list,
                        help_text="예: [{'thickness':1.0,'day':10}, {'thickness':1.5,'day':17}]",
                        verbose_name="기초두께별 소요일 데이터",
                    ),
                ),
                (
                    "floor_height_data",
                    models.JSONField(
                        default=list,
                        help_text="예: [{'height':3.5,'day':33}, {'height':4.2,'day':40}]",
                        verbose_name="층고별 소요일 데이터",
                    ),
                ),
                (
                    "change_transfer",
                    models.PositiveIntegerField(default=45, verbose_name="전이층"),
                ),
                (
                    "change_setting",
                    models.PositiveIntegerField(default=20, verbose_name="세팅층"),
                ),
                (
                    "change_refuge",
                    models.PositiveIntegerField(default=45, verbose_name="피난층"),
                ),
                (
                    "change_piloti",
                    models.PositiveIntegerField(default=40, verbose_name="필로티"),
                ),
                (
                    "change_podium",
                    models.PositiveIntegerField(default=30, verbose_name="포디움"),
                ),
                (
                    "change_sky",
                    models.PositiveIntegerField(default=60, verbose_name="스카이라운지"),
                ),
                (
                    "change_cycle_time",
                    models.PositiveIntegerField(default=8, verbose_name="Cycle Time"),
                ),
                (
                    "transfer_height_data",
                    models.JSONField(
                        default=list,
                        help_text="예: [{'floors':20,'day':30}, {'floors':40,'day':45}]",
                        verbose_name="층 수에 따른 전이층 소요일",
                    ),
                ),
                (
                    "form_tc",
                    models.PositiveIntegerField(default=20, verbose_name="TC 인양식"),
                ),
                (
                    "form_hydraulic",
                    models.PositiveIntegerField(default=30, verbose_name="유압 인양식"),
                ),
                (
                    "reverse_excavation",
                    models.PositiveIntegerField(default=25, verbose_name="역타공법 적용"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FrameWorkInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_thickness",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.2,
                        max_digits=4,
                        verbose_name="기초 두께(m)",
                    ),
                ),
                (
                    "base_working_day",
                    models.PositiveIntegerField(
                        default=11, verbose_name="기초골조 Working Day"
                    ),
                ),
                (
                    "base_calendar_day",
                    models.PositiveIntegerField(
                        default=17, verbose_name="기초골조 Calendar Day"
                    ),
                ),
                ("is_TC", models.BooleanField(default=True)),
                (
                    "cycle_time",
                    models.PositiveIntegerField(
                        default=8, verbose_name="Cycle Time (Calendar Day)"
                    ),
                ),
                (
                    "floor_height_data",
                    models.JSONField(
                        default=dict,
                        help_text="예시: {'basement': [  {'floor': 10, 'height': 3.5, 'floor_sep': '전이층, 세팅층, 피난층, 필로티, 포디움, 스카이라운지, Cycle Time 택1'},   {'floor': 9, 'height': 3.3, 'floor_sep': '전이층, 세팅층, 피난층, 필로티, 포디움, 스카이라운지, Cycle Time 택1'}], 'ground': [  {'floor': 1F, 'height': 3.2, 'floor_sep': '전이층, 세팅층, 피난층, 필로티, 포디움, 스카이라운지, Cycle Time 택1'},   {'floor': 2F, 'height': 3.1, 'floor_sep': '전이층, 세팅층, 피난층, 필로티, 포디움, 스카이라운지, Cycle Time 택1'}]}",
                        verbose_name="층고 입력 데이터",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "골조공사 입력",
                "verbose_name_plural": "골조공사 입력 목록",
            },
        ),
        migrations.CreateModel(
            name="PreparationPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preparation_fixed_months",
                    models.CharField(
                        default="0.5개월 고정", max_length=50, verbose_name="준비기간(고정 개월)"
                    ),
                ),
                (
                    "preparation_input_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="사용자 직접 입력 시 우선 적용",
                        null=True,
                        verbose_name="준비기간(직접 입력 일수)",
                    ),
                ),
                ("is_home", models.BooleanField(default=True)),
                (
                    "floors_under_months",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="사용자 직접 입력 시 우선 적용",
                        null=True,
                        verbose_name="마감공사 (직접 입력 일수)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "준비/정리 기간 및 추가공사기간",
                "verbose_name_plural": "준비/정리 기간 및 추가공사기간 목록",
            },
        ),
        migrations.CreateModel(
            name="PreparationWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "residential_days",
                    models.PositiveIntegerField(default=45, verbose_name="주거시설 소요일(일)"),
                ),
                (
                    "non_residential_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="비주거시설 소요일(일)"
                    ),
                ),
                (
                    "units_under_2000",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="2000세대 이하 추가(개월)",
                    ),
                ),
                (
                    "units_2000_3000",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=5,
                        verbose_name="2000~3000세대 추가(개월)",
                    ),
                ),
                (
                    "units_over_3000",
                    models.DecimalField(
                        decimal_places=2,
                        default=2,
                        max_digits=5,
                        verbose_name="3000세대 이상 추가(개월)",
                    ),
                ),
                (
                    "floors_under_10",
                    models.DecimalField(
                        decimal_places=2,
                        default=5.5,
                        max_digits=5,
                        verbose_name="10F 이하(개월)",
                    ),
                ),
                (
                    "floors_under_15",
                    models.DecimalField(
                        decimal_places=2,
                        default=6.6,
                        max_digits=5,
                        verbose_name="15F 이하(개월)",
                    ),
                ),
                (
                    "floors_under_20",
                    models.DecimalField(
                        decimal_places=2,
                        default=7.7,
                        max_digits=5,
                        verbose_name="20F 이하(개월)",
                    ),
                ),
                (
                    "floors_under_30",
                    models.DecimalField(
                        decimal_places=2,
                        default=8.8,
                        max_digits=5,
                        verbose_name="30F 이하(개월)",
                    ),
                ),
                (
                    "floors_under_45",
                    models.DecimalField(
                        decimal_places=2,
                        default=9.9,
                        max_digits=5,
                        verbose_name="45F 이하(개월)",
                    ),
                ),
                (
                    "floors_over_46",
                    models.DecimalField(
                        decimal_places=2,
                        default=11.0,
                        max_digits=5,
                        verbose_name="46F 이상(개월)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="프로젝트명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_delete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WorkCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "earthwork_type",
                    models.CharField(
                        choices=[(7, 7), (6, 6), (5, 5)],
                        default=7,
                        max_length=20,
                        verbose_name="토공사 근무 조건",
                    ),
                ),
                (
                    "framework_type",
                    models.CharField(
                        choices=[(7, 7), (6, 6), (5, 5)],
                        default=7,
                        max_length=20,
                        verbose_name="골조공사 근무 조건",
                    ),
                ),
                (
                    "earthwork_utilization_input",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="직접 입력한 토공사 가동률(%)",
                        max_digits=5,
                        verbose_name="직접 입력 가동률(토공사, %)",
                    ),
                ),
                (
                    "framework_utilization_input",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="직접 입력한 골조공사 가동률(%)",
                        max_digits=5,
                        null=True,
                        verbose_name="직접 입력 가동률(골조공사, %)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "근무조건 및 가동률",
                "verbose_name_plural": "근무조건 및 가동률 목록",
            },
        ),
        migrations.CreateModel(
            name="WorkScheduleWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EARTH", "토공사"),
                            ("FRAME", "골조공사"),
                            ("EXT_FIN", "외부 마감공사"),
                            ("INT_FIN", "내부 마감공사"),
                            ("POUR", "골조 타설"),
                        ],
                        help_text="공종 타입",
                        max_length=16,
                    ),
                ),
                (
                    "pct_7d",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="주7일 작업 시 적용 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="주7일(%)",
                    ),
                ),
                (
                    "pct_6d",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="주6일 작업 시 적용 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="주6일(%)",
                    ),
                ),
                (
                    "pct_5d",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="주5일 작업 시 적용 비율(%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="주5일(%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
