# Generated by Django 4.2.23 on 2026-02-20 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cpe_module", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                help_text="프로젝트 소유 사용자",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="preparationwork",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preparation_works",
                to="cpe_module.project",
            ),
        ),
        migrations.AddField(
            model_name="preparationperiod",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preparation_period",
                to="cpe_module.project",
            ),
        ),
        migrations.AddField(
            model_name="frameworkinput",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="framework_inputs",
                to="cpe_module.project",
            ),
        ),
        migrations.AddField(
            model_name="framework",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frameworks",
                to="cpe_module.project",
            ),
        ),
        migrations.AddField(
            model_name="earthworkinput",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earthwork_inputs",
                to="cpe_module.project",
            ),
        ),
        migrations.AddField(
            model_name="earthwork",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earthworks",
                to="cpe_module.project",
            ),
        ),
        migrations.AddField(
            model_name="constructionoverview",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="construction_overview",
                to="cpe_module.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="workscheduleweight",
            constraint=models.UniqueConstraint(
                fields=("project", "main_category"),
                name="unique_project_main_category_operating_rate",
            ),
        ),
    ]
