# Generated by Django 5.2.5 on 2025-10-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcondition",
            name="is_earthwork_input",
            field=models.BooleanField(default=False, help_text="토공사 가동률 직접입력 여부"),
        ),
        migrations.AddField(
            model_name="workcondition",
            name="is_framework_input",
            field=models.BooleanField(default=False, help_text="골조공사 가동률 직접입력 여부"),
        ),
        migrations.AlterField(
            model_name="workcondition",
            name="earthwork_utilization_input",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="직접 입력한 토공사 가동률(%)",
                max_digits=5,
                null=True,
                verbose_name="직접 입력 가동률(토공사, %)",
            ),
        ),
    ]
