# Generated by Django 5.2.5 on 2025-10-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0003_workcondition_is_earthwork_input_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="earthworkinput",
            name="surcharge_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=5,
                null=True,
                verbose_name="할증비율(직접입력 필드)",
            ),
        ),
    ]
