# Generated by Django 5.2.5 on 2025-10-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0004_earthworkinput_surcharge_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="preparationperiod",
            name="household",
            field=models.CharField(
                choices=[
                    ("2000 이하", "2000세대 이하"),
                    ("2000~3000세대", "2000~3000세대"),
                    ("3000 이상", "3000세대 이상"),
                ],
                default="2000~3000세대",
                max_length=20,
                verbose_name="세대수 선택",
            ),
        ),
        migrations.AddField(
            model_name="preparationperiod",
            name="is_floors_under_months",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preparationperiod",
            name="is_preparation_input_days",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="frameworkinput",
            name="floor_height_data",
            field=models.JSONField(
                default=dict,
                help_text="예시: {'basement': [  {'floor': 10, 'height': 3.5, 'floor_sep': '전이층, 세팅층, 피난층, 필로티, 포디움, 스카이라운지, Cycle Time 택1'},   {'floor': 9, 'height': 3.3, 'floor_sep': '전이층, 세팅층, 피난층, 필로티, 포디움, 스카이라운지, Cycle Time 택1'}], 'ground': [  {'floor': 1, 'height': 3.2, 'is_parallelism: Boolean' 'floor_sep': '전이층, 세팅층, 피난층, 필로티, 포디움, 스카이라운지, Cycle Time 택1'},   {'floor': 2, 'height': 3.1, 'floor_sep': '전이층, 세팅층, 피난층, 필로티, 포디움, 스카이라운지, Cycle Time 택1'}]}",
                verbose_name="층고 입력 데이터",
            ),
        ),
    ]
