# Generated by Django 5.2.5 on 2025-10-28 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0005_preparationperiod_household_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preparation_period",
                    models.PositiveIntegerField(default=0, verbose_name="준비기간"),
                ),
                (
                    "earth_retention",
                    models.PositiveIntegerField(default=0, verbose_name="흙막이가시설"),
                ),
                ("support", models.PositiveIntegerField(default=0, verbose_name="지보공")),
                (
                    "excavation",
                    models.PositiveIntegerField(default=0, verbose_name="터파기"),
                ),
                (
                    "designated_work",
                    models.PositiveIntegerField(default=0, verbose_name="지정공사"),
                ),
                (
                    "base_framework",
                    models.PositiveIntegerField(default=0, verbose_name="기초골조"),
                ),
                (
                    "basement_framework",
                    models.PositiveIntegerField(default=0, verbose_name="지하골조"),
                ),
                (
                    "ground_framework",
                    models.PositiveIntegerField(default=0, verbose_name="지상골조"),
                ),
                (
                    "finishing_work",
                    models.PositiveIntegerField(default=0, verbose_name="마감공사"),
                ),
                (
                    "additional_period",
                    models.PositiveIntegerField(default=0, verbose_name="추가기간"),
                ),
                (
                    "cleanup_period",
                    models.PositiveIntegerField(default=0, verbose_name="정리기간"),
                ),
                (
                    "remark_preparation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="준비기간 비고"
                    ),
                ),
                (
                    "remark_earth_retention",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="흙막이가시설 비고"
                    ),
                ),
                (
                    "remark_support",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="지보공 비고"
                    ),
                ),
                (
                    "remark_excavation",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="터파기 비고"
                    ),
                ),
                (
                    "remark_designated_work",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="지정공사 비고"
                    ),
                ),
                (
                    "remark_earthwork_total",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="토공사 소계 비고"
                    ),
                ),
                (
                    "remark_base_framework",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="기초골조 비고"
                    ),
                ),
                (
                    "remark_basement_framework",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="지하골조 비고"
                    ),
                ),
                (
                    "remark_ground_framework",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="지상골조 비고"
                    ),
                ),
                (
                    "remark_framework_total",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="골조공사 소계 비고"
                    ),
                ),
                (
                    "remark_finishing_work",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="마감공사 비고"
                    ),
                ),
                (
                    "remark_additional_period",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="추가기간 비고"
                    ),
                ),
                (
                    "remark_cleanup_period",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="정리기간 비고"
                    ),
                ),
                (
                    "remark_total",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="합계 비고"
                    ),
                ),
                (
                    "ai_response",
                    models.TextField(blank=True, null=True, verbose_name="AI 분석 결과"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        db_column="project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation_project",
                        to="cpe_module.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "공사기간 견적서",
                "verbose_name_plural": "공사기간 견적서 목록",
            },
        ),
    ]
