# Generated by Django 5.2.5 on 2025-10-28 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0006_quotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="earthwork",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="framework",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preparationwork",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="earthwork",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="earthworks",
                to="cpe_module.project",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="frameworks",
                to="cpe_module.project",
            ),
        ),
        migrations.AlterField(
            model_name="preparationwork",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preparation_works",
                to="cpe_module.project",
            ),
        ),
    ]
