# Generated by Django 5.2.5 on 2025-10-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0007_earthwork_is_admin_framework_is_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="frameworkinput",
            name="base_calendar_day",
        ),
        migrations.RemoveField(
            model_name="frameworkinput",
            name="base_working_day",
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="adjacent_road",
            field=models.CharField(
                blank=True,
                default="1.0 도로",
                max_length=100,
                null=True,
                verbose_name="인접도로",
            ),
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="adjacent_side_count",
            field=models.PositiveIntegerField(default=2, verbose_name="도로 접한 면 수"),
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="elevation_max",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                max_digits=5,
                null=True,
                verbose_name="최고 고저차(m)",
            ),
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="elevation_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.1,
                max_digits=5,
                null=True,
                verbose_name="최저 고저차(m)",
            ),
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="location",
            field=models.CharField(
                blank=True, default="서울", max_length=100, null=True, verbose_name="위치"
            ),
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="nearby_env",
            field=models.CharField(
                blank=True,
                choices=[
                    ("학교", "학교"),
                    ("주거지", "주거지"),
                    ("노후시설", "노후시설"),
                    ("문화재", "문화재"),
                    ("택지개발", "택지개발"),
                ],
                default="학교",
                max_length=50,
                null=True,
                verbose_name="주변현황",
            ),
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="site_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=12000,
                max_digits=10,
                null=True,
                verbose_name="대지면적(㎡)",
            ),
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="total_buildings",
            field=models.PositiveIntegerField(default=4, verbose_name="동수"),
        ),
        migrations.AlterField(
            model_name="constructionoverview",
            name="total_floor_area",
            field=models.DecimalField(
                decimal_places=2, default=10000, max_digits=12, verbose_name="연면적(㎡)"
            ),
        ),
        migrations.AlterField(
            model_name="earthworkinput",
            name="special_retention_extra_days",
            field=models.PositiveIntegerField(
                blank=True, default=15, null=True, verbose_name="특수 흙막이 추가 작업일수"
            ),
        ),
        migrations.AlterField(
            model_name="preparationperiod",
            name="floors_under_months",
            field=models.PositiveIntegerField(
                blank=True,
                default=1.1,
                help_text="사용자 직접 입력 시 우선 적용",
                null=True,
                verbose_name="마감공사 (직접 입력 일수)",
            ),
        ),
        migrations.AlterField(
            model_name="preparationperiod",
            name="preparation_input_days",
            field=models.PositiveIntegerField(
                blank=True,
                default=30,
                help_text="사용자 직접 입력 시 우선 적용",
                null=True,
                verbose_name="준비기간(직접 입력 일수)",
            ),
        ),
        migrations.AlterField(
            model_name="workcondition",
            name="earthwork_utilization_input",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=70.91,
                help_text="직접 입력한 토공사 가동률(%)",
                max_digits=5,
                null=True,
                verbose_name="직접 입력 가동률(토공사, %)",
            ),
        ),
        migrations.AlterField(
            model_name="workcondition",
            name="framework_utilization_input",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=65.62,
                help_text="직접 입력한 골조공사 가동률(%)",
                max_digits=5,
                null=True,
                verbose_name="직접 입력 가동률(골조공사, %)",
            ),
        ),
    ]
