# Generated by Django 5.2.5 on 2025-10-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0008_remove_frameworkinput_base_calendar_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earthworkinput",
            name="designated_diameter",
            field=models.CharField(
                default="1000", max_length=5, verbose_name="RCD/PRD 직경(mm)"
            ),
        ),
    ]
