# Generated by Django 5.2.5 on 2026-01-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0010_project_calc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="공사 시작일"),
        ),
    ]
