# Generated by Django 5.2.5 on 2026-01-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0011_project_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workscheduleweight",
            options={
                "ordering": ["project", "main_category"],
                "verbose_name": "가동률",
                "verbose_name_plural": "가동률 목록",
            },
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="climate_days_excl_dup",
            field=models.IntegerField(
                default=0,
                help_text="기후 조건으로 작업 불가능한 일수 (중복 제외)",
                verbose_name="기후불능일(중복제외)",
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="legal_holidays",
            field=models.IntegerField(
                default=0, help_text="공공/민간 구분에 따른 법정공휴일 수", verbose_name="법정공휴일"
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="main_category",
            field=models.CharField(
                default="",
                help_text="e.g., '1. 공사준비', '2. 토공사', '3. 골조공사'",
                max_length=100,
                verbose_name="대공종",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="operating_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="최종 가동률 (계산 또는 입력)",
                max_digits=5,
                verbose_name="가동률(%)",
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="rainfall_threshold",
            field=models.CharField(
                blank=True, default="10mm 이상", max_length=50, verbose_name="강우량"
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="snowfall_threshold",
            field=models.CharField(
                blank=True, default="0.3 이상", max_length=50, verbose_name="강설량"
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="summer_threshold",
            field=models.CharField(
                blank=True, default="35℃ 이상", max_length=50, verbose_name="혹서기"
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="visibility_threshold",
            field=models.CharField(
                blank=True, default="미적용", max_length=50, verbose_name="비시정"
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="wind_threshold",
            field=models.CharField(
                blank=True, default="15m/s 이상", max_length=50, verbose_name="순간대풍속"
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="winter_threshold",
            field=models.CharField(
                blank=True, default="최저 5℃ 이하", max_length=50, verbose_name="동절기"
            ),
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="working_days",
            field=models.IntegerField(
                default=0, help_text="연간 작업 가능일수", verbose_name="작업일"
            ),
        ),
        migrations.AlterField(
            model_name="workscheduleweight",
            name="pct_5d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="[DEPRECATED]",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workscheduleweight",
            name="pct_6d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="[DEPRECATED]",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workscheduleweight",
            name="pct_7d",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="[DEPRECATED]",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workscheduleweight",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="[DEPRECATED] Use main_category instead",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="workscheduleweight",
            constraint=models.UniqueConstraint(
                fields=("project", "main_category"),
                name="unique_project_main_category_operating_rate",
            ),
        ),
    ]
