# Generated by Django 5.2.5 on 2026-01-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0015_add_operating_rate_threshold_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcondition",
            name="region",
            field=models.CharField(
                blank=True,
                default="서울",
                help_text="기상 데이터 조회 지역",
                max_length=50,
                null=True,
                verbose_name="지역",
            ),
        ),
    ]
