# Generated by Django 5.2.5 on 2026-01-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0016_add_region_to_workcondition"),
    ]

    operations = [
        migrations.AddField(
            model_name="workscheduleweight",
            name="work_week_days",
            field=models.IntegerField(
                choices=[(7, "7일"), (6, "6일"), (5, "5일")],
                default=6,
                help_text="7일, 6일, 5일 중 선택",
                verbose_name="주간 작업일",
            ),
        ),
    ]
