# Generated by Django 5.2.5 on 2026-01-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0017_add_work_week_days_to_workscheduleweight"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcondition",
            name="winter_criteria",
            field=models.CharField(
                choices=[("MIN", "최저기온"), ("AVG", "평균기온"), ("MAX", "최고기온")],
                default="AVG",
                help_text="동절기 판단 기준 온도 (최저/평균/최고)",
                max_length=10,
                verbose_name="동절기 기준",
            ),
        ),
        migrations.AlterField(
            model_name="workscheduleweight",
            name="winter_threshold",
            field=models.CharField(
                blank=True, default="평균 5℃ 이하", max_length=50, verbose_name="동절기"
            ),
        ),
    ]
