# Generated by Django 5.2.5 on 2026-01-29 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0018_workcondition_winter_criteria_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workcondition",
            name="winter_criteria",
        ),
        migrations.AddField(
            model_name="workscheduleweight",
            name="winter_criteria",
            field=models.CharField(
                choices=[("MIN", "최저기온"), ("AVG", "평균기온"), ("MAX", "최고기온")],
                default="AVG",
                max_length=10,
                verbose_name="동절기 기준",
            ),
        ),
    ]
