# Generated by Django 5.2.5 on 2026-01-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_module", "0019_remove_workcondition_winter_criteria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workcondition",
            name="data_years",
            field=models.IntegerField(
                default=10,
                help_text="기상 데이터 분석 기간 (최근 N년)",
                verbose_name="데이터 적용 기간(년)",
            ),
        ),
    ]
