# Generated by Django 5.2.5 on 2026-01-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.IntegerField(unique=True, verbose_name="지점")),
                ("name", models.CharField(max_length=100, verbose_name="지점명")),
            ],
            options={
                "verbose_name": "지점",
                "verbose_name_plural": "지점 목록",
                "ordering": ["station_id"],
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="날짜")),
                ("name", models.CharField(max_length=100, verbose_name="공휴일명")),
                (
                    "date_kind",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="날짜종류"
                    ),
                ),
                (
                    "is_holiday",
                    models.CharField(default="Y", max_length=1, verbose_name="공휴일여부"),
                ),
                ("is_private", models.BooleanField(default=False, verbose_name="민간적용")),
                ("seq", models.IntegerField(default=1, verbose_name="순서")),
                ("locdate", models.IntegerField(verbose_name="원본날짜코드")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "공휴일",
                "verbose_name_plural": "공휴일 목록",
                "ordering": ["date", "seq"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "seq"), name="uniq_public_holiday"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WeatherDailyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.IntegerField(verbose_name="지점")),
                ("date", models.DateField(verbose_name="일자")),
                ("tm", models.DateField(blank=True, null=True, verbose_name="tm")),
                (
                    "stnId",
                    models.IntegerField(blank=True, null=True, verbose_name="stnId"),
                ),
                (
                    "stnNm",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="stnNm"
                    ),
                ),
                (
                    "avgCm10Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgCm10Te"),
                ),
                (
                    "avgCm20Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgCm20Te"),
                ),
                (
                    "avgCm30Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgCm30Te"),
                ),
                (
                    "avgCm5Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgCm5Te"),
                ),
                (
                    "avgLmac",
                    models.FloatField(blank=True, null=True, verbose_name="avgLmac"),
                ),
                (
                    "avgM05Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgM05Te"),
                ),
                (
                    "avgM10Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgM10Te"),
                ),
                (
                    "avgM15Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgM15Te"),
                ),
                (
                    "avgM30Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgM30Te"),
                ),
                (
                    "avgM50Te",
                    models.FloatField(blank=True, null=True, verbose_name="avgM50Te"),
                ),
                (
                    "avgPa",
                    models.FloatField(blank=True, null=True, verbose_name="avgPa"),
                ),
                (
                    "avgPs",
                    models.FloatField(blank=True, null=True, verbose_name="avgPs"),
                ),
                (
                    "avgPv",
                    models.FloatField(blank=True, null=True, verbose_name="avgPv"),
                ),
                (
                    "avgRhm",
                    models.FloatField(blank=True, null=True, verbose_name="avgRhm"),
                ),
                (
                    "avgTa",
                    models.FloatField(blank=True, null=True, verbose_name="avgTa"),
                ),
                (
                    "avgTca",
                    models.FloatField(blank=True, null=True, verbose_name="avgTca"),
                ),
                (
                    "avgTd",
                    models.FloatField(blank=True, null=True, verbose_name="avgTd"),
                ),
                (
                    "avgTs",
                    models.FloatField(blank=True, null=True, verbose_name="avgTs"),
                ),
                (
                    "avgWs",
                    models.FloatField(blank=True, null=True, verbose_name="avgWs"),
                ),
                (
                    "ddMefs",
                    models.FloatField(blank=True, null=True, verbose_name="ddMefs"),
                ),
                (
                    "ddMefsHrmt",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ddMefsHrmt"
                    ),
                ),
                (
                    "ddMes",
                    models.FloatField(blank=True, null=True, verbose_name="ddMes"),
                ),
                (
                    "ddMesHrmt",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="ddMesHrmt"
                    ),
                ),
                (
                    "hr1MaxIcsr",
                    models.FloatField(blank=True, null=True, verbose_name="hr1MaxIcsr"),
                ),
                (
                    "hr1MaxIcsrHrmt",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="hr1MaxIcsrHrmt",
                    ),
                ),
                (
                    "hr1MaxRn",
                    models.FloatField(blank=True, null=True, verbose_name="hr1MaxRn"),
                ),
                (
                    "hr1MaxRnHrmt",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="hr1MaxRnHrmt",
                    ),
                ),
                (
                    "hr24SumRws",
                    models.FloatField(blank=True, null=True, verbose_name="hr24SumRws"),
                ),
                ("iscs", models.FloatField(blank=True, null=True, verbose_name="iscs")),
                (
                    "maxInsWs",
                    models.FloatField(blank=True, null=True, verbose_name="maxInsWs"),
                ),
                (
                    "maxInsWsHrmt",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="maxInsWsHrmt",
                    ),
                ),
                (
                    "maxInsWsWd",
                    models.FloatField(blank=True, null=True, verbose_name="maxInsWsWd"),
                ),
                (
                    "maxPs",
                    models.FloatField(blank=True, null=True, verbose_name="maxPs"),
                ),
                (
                    "maxPsHrmt",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="maxPsHrmt"
                    ),
                ),
                (
                    "maxTa",
                    models.FloatField(blank=True, null=True, verbose_name="maxTa"),
                ),
                (
                    "maxTaHrmt",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="maxTaHrmt"
                    ),
                ),
                (
                    "maxWd",
                    models.FloatField(blank=True, null=True, verbose_name="maxWd"),
                ),
                (
                    "maxWs",
                    models.FloatField(blank=True, null=True, verbose_name="maxWs"),
                ),
                (
                    "maxWsHrmt",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="maxWsHrmt"
                    ),
                ),
                (
                    "maxWsWd",
                    models.FloatField(blank=True, null=True, verbose_name="maxWsWd"),
                ),
                (
                    "mi10MaxRn",
                    models.FloatField(blank=True, null=True, verbose_name="mi10MaxRn"),
                ),
                (
                    "mi10MaxRnHrmt",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="mi10MaxRnHrmt",
                    ),
                ),
                (
                    "minPs",
                    models.FloatField(blank=True, null=True, verbose_name="minPs"),
                ),
                (
                    "minPsHrmt",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="minPsHrmt"
                    ),
                ),
                (
                    "minRhm",
                    models.FloatField(blank=True, null=True, verbose_name="minRhm"),
                ),
                (
                    "minRhmHrmt",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="minRhmHrmt"
                    ),
                ),
                (
                    "minTa",
                    models.FloatField(blank=True, null=True, verbose_name="minTa"),
                ),
                (
                    "minTaHrmt",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="minTaHrmt"
                    ),
                ),
                (
                    "minTg",
                    models.FloatField(blank=True, null=True, verbose_name="minTg"),
                ),
                (
                    "n99Rn",
                    models.FloatField(blank=True, null=True, verbose_name="n99Rn"),
                ),
                (
                    "ssDur",
                    models.FloatField(blank=True, null=True, verbose_name="ssDur"),
                ),
                (
                    "sumDpthFhsc",
                    models.FloatField(
                        blank=True, null=True, verbose_name="sumDpthFhsc"
                    ),
                ),
                (
                    "sumFogDur",
                    models.FloatField(blank=True, null=True, verbose_name="sumFogDur"),
                ),
                (
                    "sumGsr",
                    models.FloatField(blank=True, null=True, verbose_name="sumGsr"),
                ),
                (
                    "sumLrgEv",
                    models.FloatField(blank=True, null=True, verbose_name="sumLrgEv"),
                ),
                (
                    "sumRn",
                    models.FloatField(blank=True, null=True, verbose_name="sumRn"),
                ),
                (
                    "sumRnDur",
                    models.FloatField(blank=True, null=True, verbose_name="sumRnDur"),
                ),
                (
                    "sumSmlEv",
                    models.FloatField(blank=True, null=True, verbose_name="sumSmlEv"),
                ),
                (
                    "sumSsHr",
                    models.FloatField(blank=True, null=True, verbose_name="sumSsHr"),
                ),
                ("payload", models.JSONField(verbose_name="원본 데이터")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "일자료",
                "verbose_name_plural": "일자료 목록",
                "ordering": ["-date", "station_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("station_id", "date"), name="uniq_weather_daily"
                    )
                ],
            },
        ),
    ]
