# Generated by Django 4.2.23 on 2026-01-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatio", "0002_alter_weatherstation_id_weatherdailyrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="날짜")),
                ("name", models.CharField(max_length=100, verbose_name="공휴일명")),
                (
                    "date_kind",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="날짜종류"
                    ),
                ),
                (
                    "is_holiday",
                    models.CharField(default="Y", max_length=1, verbose_name="공휴일여부"),
                ),
                ("seq", models.IntegerField(default=1, verbose_name="순서")),
                ("locdate", models.IntegerField(verbose_name="원본날짜코드")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일")),
            ],
            options={
                "verbose_name": "공휴일",
                "verbose_name_plural": "공휴일 목록",
                "ordering": ["date", "seq"],
            },
        ),
        migrations.AddConstraint(
            model_name="publicholiday",
            constraint=models.UniqueConstraint(
                fields=("date", "seq"), name="uniq_public_holiday"
            ),
        ),
    ]
