# Generated by Django 5.2.5 on 2026-01-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatio", "0003_publicholiday_publicholiday_uniq_public_holiday"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicholiday",
            name="sector_type",
            field=models.CharField(
                choices=[("PUBLIC", "공공만"), ("PRIVATE", "민간만"), ("BOTH", "공공+민간")],
                default="PUBLIC",
                max_length=10,
                verbose_name="적용 대상",
            ),
        ),
    ]
