# Generated by Django 5.2.5 on 2026-01-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatio", "0004_publicholiday_sector_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicholiday",
            name="sector_type",
            field=models.CharField(
                choices=[("PUBLIC", "공공"), ("PRIVATE", "민간"), ("BOTH", "공공+민간")],
                default="PUBLIC",
                max_length=10,
                verbose_name="적용섹터",
            ),
        ),
    ]
