# Generated by Django 5.2.5 on 2026-01-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatio", "0005_alter_publicholiday_sector_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicholiday",
            name="sector_type",
        ),
        migrations.AddField(
            model_name="publicholiday",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="민간공휴일"),
        ),
    ]
