# Generated by Django 4.2.23 on 2026-01-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operatio", "0006_remove_publicholiday_sector_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicholiday",
            name="is_private",
            field=models.BooleanField(default=False, verbose_name="민간적용"),
        ),
    ]
