# Generated by Django 4.2.23 on 2026-02-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoredPileProductivityBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="비고/설명")),
                (
                    "t1",
                    models.FloatField(
                        default=2.0, help_text="입력값 (시간)", verbose_name="준비시간(t1)"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="굴착 공법"
                    ),
                ),
                (
                    "pile_diameter",
                    models.FloatField(
                        default=0.0, help_text="입력값", verbose_name="말뚝 직경(mm)"
                    ),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="점질토 깊이"
                    ),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="사질토 깊이"
                    ),
                ),
                (
                    "layer_depth_gravel",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="자갈 깊이"
                    ),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="풍화암 깊이"
                    ),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="연암 깊이"
                    ),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="경암 깊이"
                    ),
                ),
                (
                    "classification_factor",
                    models.FloatField(
                        default=0.85, help_text="입력값", verbose_name="작업계수(f)"
                    ),
                ),
                (
                    "total_depth",
                    models.FloatField(
                        default=0.0, help_text="계산값", verbose_name="굴착 깊이 합계(m)"
                    ),
                ),
                (
                    "t2",
                    models.FloatField(
                        default=0.0, help_text="계산값 (시간)", verbose_name="천공시간(t2)"
                    ),
                ),
                (
                    "cycle_time",
                    models.FloatField(
                        default=0.0, help_text="계산값 (시간)", verbose_name="본당 소요시간(T)"
                    ),
                ),
                (
                    "daily_production_count",
                    models.FloatField(
                        default=0.0, help_text="계산값 (8/T)", verbose_name="일일 작업량(본)"
                    ),
                ),
                (
                    "calculation_formula",
                    models.CharField(
                        blank=True, help_text="참고용", max_length=255, verbose_name="계산식"
                    ),
                ),
            ],
            options={
                "verbose_name": "현장타설말뚝 생산성 근거",
                "verbose_name_plural": "현장타설말뚝 생산성 근거 목록",
            },
        ),
        migrations.CreateModel(
            name="BoredPileResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_selection",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="공법 선택"
                    ),
                ),
                (
                    "diameter_selection",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="직경 규격(선택)"
                    ),
                ),
                (
                    "method_clay",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="점질토 공법"
                    ),
                ),
                (
                    "method_sand",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="사질토 공법"
                    ),
                ),
                (
                    "method_gravel",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="자갈 공법"
                    ),
                ),
                (
                    "method_weathered",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="풍화암 공법"
                    ),
                ),
                (
                    "method_soft_rock",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="연암 공법"
                    ),
                ),
                (
                    "method_hard_rock",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="경암 공법"
                    ),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(default=0.0, verbose_name="점질토 깊이(m)"),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(default=0.0, verbose_name="사질토 깊이(m)"),
                ),
                (
                    "layer_depth_gravel",
                    models.FloatField(default=0.0, verbose_name="자갈 깊이(m)"),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(default=0.0, verbose_name="풍화암 깊이(m)"),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(default=0.0, verbose_name="연암 깊이(m)"),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(default=0.0, verbose_name="경암 깊이(m)"),
                ),
                ("t1", models.FloatField(default=2.0, verbose_name="준비시간(t1, 시간)")),
                (
                    "classification_factor",
                    models.FloatField(default=0.85, verbose_name="작업계수(f)"),
                ),
                (
                    "total_depth",
                    models.FloatField(default=0.0, verbose_name="합계 깊이(m)"),
                ),
                ("t2", models.FloatField(default=0.0, verbose_name="천공 시간(t2, 시간)")),
                (
                    "cycle_time",
                    models.FloatField(default=0.0, verbose_name="본당 작업시간(시간)"),
                ),
                (
                    "daily_production_count",
                    models.FloatField(default=0.0, verbose_name="일일 생산성(본)"),
                ),
            ],
            options={
                "verbose_name": "현장타설말뚝 결과 요약",
                "verbose_name_plural": "현장타설말뚝 결과 요약 목록",
            },
        ),
        migrations.CreateModel(
            name="BoredPileStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("RCD", "R.C.D"),
                            ("OSCILLATOR", "요동식"),
                            ("ALL_CASING", "전회전식"),
                        ],
                        max_length=20,
                        verbose_name="공법",
                    ),
                ),
                (
                    "diameter_spec",
                    models.CharField(
                        help_text="예: 1000, 1500, 2000, 2500, 3000",
                        max_length=50,
                        verbose_name="말뚝직경 규격",
                    ),
                ),
                (
                    "value_clay",
                    models.FloatField(blank=True, null=True, verbose_name="점질토"),
                ),
                (
                    "value_sand",
                    models.FloatField(blank=True, null=True, verbose_name="사질토"),
                ),
                (
                    "value_gravel",
                    models.FloatField(blank=True, null=True, verbose_name="자갈"),
                ),
                (
                    "value_weathered",
                    models.FloatField(blank=True, null=True, verbose_name="풍화암"),
                ),
                (
                    "value_soft_rock",
                    models.FloatField(blank=True, null=True, verbose_name="연암"),
                ),
                (
                    "value_hard_rock",
                    models.FloatField(blank=True, null=True, verbose_name="경암"),
                ),
            ],
            options={
                "verbose_name": "현장타설말뚝 천공 기준",
                "verbose_name_plural": "현장타설말뚝 천공 기준 목록",
            },
        ),
        migrations.CreateModel(
            name="CIPDrillingStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bit_type",
                    models.CharField(
                        choices=[
                            ("AUGER", "오거비트"),
                            ("IMPROVED", "개량형비트"),
                            ("HAMMER", "해머비트"),
                        ],
                        max_length=20,
                        verbose_name="비트 타입",
                    ),
                ),
                (
                    "diameter_spec",
                    models.CharField(
                        help_text="예: 500미만, 500이상, 500~600",
                        max_length=50,
                        verbose_name="말뚝직경 규격",
                    ),
                ),
                (
                    "value_clay",
                    models.FloatField(blank=True, null=True, verbose_name="점질토"),
                ),
                (
                    "value_sand",
                    models.FloatField(blank=True, null=True, verbose_name="사질토"),
                ),
                (
                    "value_weathered",
                    models.FloatField(blank=True, null=True, verbose_name="풍화암"),
                ),
                (
                    "value_soft_rock",
                    models.FloatField(blank=True, null=True, verbose_name="연암"),
                ),
                (
                    "value_hard_rock",
                    models.FloatField(blank=True, null=True, verbose_name="경암"),
                ),
                (
                    "value_mixed",
                    models.FloatField(blank=True, null=True, verbose_name="혼합층"),
                ),
            ],
            options={
                "verbose_name": "CIP 천공 기준(표준품셈)",
                "verbose_name_plural": "CIP 천공 기준 목록",
            },
        ),
        migrations.CreateModel(
            name="CIPProductivityBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="비고/설명")),
                (
                    "t1",
                    models.FloatField(
                        default=3.0, help_text="입력값 (분)", verbose_name="준비시간(t1)"
                    ),
                ),
                (
                    "drill_diameter",
                    models.FloatField(
                        default=0.0, help_text="입력값", verbose_name="천공 직경(mm)"
                    ),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="점질토 깊이"
                    ),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="사질토 깊이"
                    ),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="풍화암 깊이"
                    ),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="연암 깊이"
                    ),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="경암 깊이"
                    ),
                ),
                (
                    "layer_depth_mixed",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="혼합층 깊이"
                    ),
                ),
                (
                    "t3",
                    models.FloatField(
                        default=2.0,
                        help_text="입력값 (분)",
                        verbose_name="철근망 및 H형강 건입(t3)",
                    ),
                ),
                (
                    "concrete_pouring_length",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="콘크리트 타설 길이(m)"
                    ),
                ),
                (
                    "classification_factor",
                    models.FloatField(
                        default=0.8, help_text="입력값", verbose_name="작업계수(f)"
                    ),
                ),
                (
                    "total_depth",
                    models.FloatField(
                        default=0.0,
                        help_text="계산값 (지층 깊이 합계)",
                        verbose_name="굴착 깊이 합계(m)",
                    ),
                ),
                (
                    "t2",
                    models.FloatField(
                        default=0.0,
                        help_text="계산값 (지층별 깊이 * 굴착속도)",
                        verbose_name="천공시간(t2)",
                    ),
                ),
                (
                    "t4",
                    models.FloatField(
                        default=0.0,
                        help_text="계산값 (타설 길이 기반)",
                        verbose_name="콘크리트 타설 시간(t4)",
                    ),
                ),
                (
                    "cycle_time",
                    models.FloatField(
                        default=0.0,
                        help_text="계산값 (t1+t2+t3+t4)",
                        verbose_name="본당 소요시간(T)",
                    ),
                ),
                (
                    "daily_production_count",
                    models.FloatField(
                        default=0.0, help_text="계산값 (480*f/T)", verbose_name="일일 작업량(공)"
                    ),
                ),
                (
                    "calculation_formula",
                    models.CharField(
                        blank=True, help_text="참고용", max_length=255, verbose_name="계산식"
                    ),
                ),
            ],
            options={
                "verbose_name": "CIP 생산성 근거",
                "verbose_name_plural": "CIP 생산성 근거 목록",
            },
        ),
        migrations.CreateModel(
            name="CIPResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diameter_selection",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="직경 규격(선택)"
                    ),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(default=0.0, verbose_name="점질토 깊이(m)"),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(default=0.0, verbose_name="사질토 깊이(m)"),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(default=0.0, verbose_name="풍화암 깊이(m)"),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(default=0.0, verbose_name="연암 깊이(m)"),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(default=0.0, verbose_name="경암 깊이(m)"),
                ),
                (
                    "layer_depth_mixed",
                    models.FloatField(default=0.0, verbose_name="혼합층 깊이(m)"),
                ),
                (
                    "bit_type_clay",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="점질토 비트"
                    ),
                ),
                (
                    "bit_type_sand",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="사질토 비트"
                    ),
                ),
                (
                    "bit_type_weathered",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="풍화암 비트"
                    ),
                ),
                (
                    "bit_type_soft_rock",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="연암 비트"
                    ),
                ),
                (
                    "bit_type_hard_rock",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="경암 비트"
                    ),
                ),
                (
                    "bit_type_mixed",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="혼합층 비트"
                    ),
                ),
                (
                    "total_depth",
                    models.FloatField(default=0.0, verbose_name="합계 깊이(m)"),
                ),
                ("t2", models.FloatField(default=0.0, verbose_name="천공 시간(t2, 분)")),
                (
                    "cycle_time",
                    models.FloatField(default=0.0, verbose_name="본당 작업시간(분)"),
                ),
                (
                    "daily_production_count",
                    models.FloatField(default=0.0, verbose_name="일일 생산성(본)"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConstructionProductivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_category", models.CharField(max_length=100, verbose_name="구분")),
                ("category", models.CharField(max_length=100, verbose_name="공종")),
                (
                    "sub_category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="세부공종"
                    ),
                ),
                (
                    "item_name",
                    models.CharField(blank=True, max_length=255, verbose_name="목차"),
                ),
                (
                    "standard",
                    models.CharField(blank=True, max_length=255, verbose_name="규격"),
                ),
                ("unit", models.CharField(max_length=50, verbose_name="단위")),
                ("crew_composition_text", models.TextField(verbose_name="산출근거(작업조)")),
                (
                    "productivity_type",
                    models.CharField(max_length=50, verbose_name="생산성 기준"),
                ),
                (
                    "skill_worker_1_pum",
                    models.FloatField(default=0.0, verbose_name="기능공1 품"),
                ),
                (
                    "skill_worker_1_count",
                    models.FloatField(default=0.0, verbose_name="기능공1 인원"),
                ),
                (
                    "skill_worker_2_pum",
                    models.FloatField(default=0.0, verbose_name="기능공2 품"),
                ),
                (
                    "skill_worker_2_count",
                    models.FloatField(default=0.0, verbose_name="기능공2 인원"),
                ),
                (
                    "special_worker_pum",
                    models.FloatField(default=0.0, verbose_name="특별인부 품"),
                ),
                (
                    "special_worker_count",
                    models.FloatField(default=0.0, verbose_name="특별인부 인원"),
                ),
                (
                    "common_worker_pum",
                    models.FloatField(default=0.0, verbose_name="보통인부 품"),
                ),
                (
                    "common_worker_count",
                    models.FloatField(default=0.0, verbose_name="보통인부 인원"),
                ),
                ("equipment_pum", models.FloatField(default=0.0, verbose_name="장비 품")),
                (
                    "equipment_count",
                    models.FloatField(default=0.0, verbose_name="장비 대수"),
                ),
                (
                    "pumsam_workload",
                    models.FloatField(default=0.0, verbose_name="표준품셈"),
                ),
                (
                    "molit_workload",
                    models.FloatField(default=0.0, verbose_name="국토부 가이드라인"),
                ),
            ],
            options={
                "verbose_name": "표준 생산성 데이터",
            },
        ),
        migrations.CreateModel(
            name="ConstructionScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=list, verbose_name="스케줄 데이터 (JSON)"
                    ),
                ),
            ],
            options={
                "verbose_name": "공기산정 상세 항목 (JSON)",
            },
        ),
        migrations.CreateModel(
            name="PileProductivityBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="설명"),
                ),
                (
                    "pile_diameter",
                    models.FloatField(default=500.0, verbose_name="말뚝직경(mm)"),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(default=0.0, verbose_name="점질토 깊이(m)"),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(default=0.0, verbose_name="사질토 깊이(m)"),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(default=0.0, verbose_name="풍화암 깊이(m)"),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(default=0.0, verbose_name="연암 깊이(m)"),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(default=0.0, verbose_name="경암 깊이(m)"),
                ),
                (
                    "layer_depth_mixed",
                    models.FloatField(default=0.0, verbose_name="혼합층 깊이(m)"),
                ),
                ("t1", models.FloatField(default=5.0, verbose_name="준비시간(t1, 분)")),
                ("t3", models.FloatField(default=8.0, verbose_name="말뚝 근입/항타(t3, 분)")),
                (
                    "grouting_length",
                    models.FloatField(default=0.0, verbose_name="그라우팅 길이(m)"),
                ),
                ("t5", models.FloatField(default=18.0, verbose_name="용접(t5, 분)")),
                (
                    "welding_diameter",
                    models.FloatField(default=500.0, verbose_name="용접 직경(mm)"),
                ),
                (
                    "classification_factor",
                    models.FloatField(default=0.85, verbose_name="작업계수(f)"),
                ),
                (
                    "total_depth",
                    models.FloatField(default=0.0, verbose_name="굴착 깊이 합계(m)"),
                ),
                ("t2", models.FloatField(default=0.0, verbose_name="항타 시간(t2, 분)")),
                ("t4", models.FloatField(default=0.0, verbose_name="그라우팅(t4, 분)")),
                (
                    "cycle_time",
                    models.FloatField(default=0.0, verbose_name="본당 소요시간(T, 분)"),
                ),
                (
                    "daily_production_count",
                    models.FloatField(default=0.0, verbose_name="일일 작업량(본)"),
                ),
                (
                    "calculation_formula",
                    models.CharField(blank=True, max_length=255, verbose_name="계산식"),
                ),
            ],
            options={
                "verbose_name": "기성말뚝 생산성 근거",
                "verbose_name_plural": "기성말뚝 생산성 근거 목록",
            },
        ),
        migrations.CreateModel(
            name="PileResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diameter_selection",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="직경 규격(선택)"
                    ),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(default=0.0, verbose_name="점질토 깊이(m)"),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(default=0.0, verbose_name="사질토 깊이(m)"),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(default=0.0, verbose_name="풍화암 깊이(m)"),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(default=0.0, verbose_name="연암 깊이(m)"),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(default=0.0, verbose_name="경암 깊이(m)"),
                ),
                (
                    "layer_depth_mixed",
                    models.FloatField(default=0.0, verbose_name="혼합층 깊이(m)"),
                ),
                (
                    "pile_type_clay",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="점질토 말뚝종류"
                    ),
                ),
                (
                    "pile_type_sand",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="사질토 말뚝종류"
                    ),
                ),
                (
                    "pile_type_weathered",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="풍화암 말뚝종류"
                    ),
                ),
                (
                    "pile_type_soft_rock",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="연암 말뚝종류"
                    ),
                ),
                (
                    "pile_type_hard_rock",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="경암 말뚝종류"
                    ),
                ),
                (
                    "pile_type_mixed",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="혼합층 말뚝종류"
                    ),
                ),
                ("t1", models.FloatField(default=5.0, verbose_name="준비시간(t1, 분)")),
                ("t3", models.FloatField(default=8.0, verbose_name="말뚝 근입/항타(t3, 분)")),
                (
                    "grouting_length",
                    models.FloatField(default=0.0, verbose_name="그라우팅 길이(m)"),
                ),
                ("t5", models.FloatField(default=18.0, verbose_name="용접(t5, 분)")),
                (
                    "welding_diameter",
                    models.FloatField(default=500.0, verbose_name="용접 직경(mm)"),
                ),
                (
                    "classification_factor",
                    models.FloatField(default=0.85, verbose_name="작업계수(f)"),
                ),
                (
                    "total_depth",
                    models.FloatField(default=0.0, verbose_name="합계 깊이(m)"),
                ),
                ("t2", models.FloatField(default=0.0, verbose_name="항타 시간(t2, 분)")),
                ("t4", models.FloatField(default=0.0, verbose_name="그라우팅(t4, 분)")),
                (
                    "cycle_time",
                    models.FloatField(default=0.0, verbose_name="본당 작업시간(분)"),
                ),
                (
                    "daily_production_count",
                    models.FloatField(default=0.0, verbose_name="일일 생산성(본)"),
                ),
            ],
            options={
                "verbose_name": "기성말뚝 결과",
                "verbose_name_plural": "기성말뚝 결과 목록",
            },
        ),
        migrations.CreateModel(
            name="PileStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pile_type",
                    models.CharField(
                        choices=[
                            ("AUGER", "오거비트"),
                            ("IMPROVED", "개량형비트"),
                            ("HAMMER", "해머비트"),
                        ],
                        max_length=20,
                        verbose_name="말뚝 종류",
                    ),
                ),
                (
                    "diameter_spec",
                    models.CharField(max_length=50, verbose_name="직경 규격"),
                ),
                (
                    "value_clay",
                    models.FloatField(blank=True, null=True, verbose_name="점질토(분/m)"),
                ),
                (
                    "value_sand",
                    models.FloatField(blank=True, null=True, verbose_name="사질토(분/m)"),
                ),
                (
                    "value_weathered",
                    models.FloatField(blank=True, null=True, verbose_name="풍화암(분/m)"),
                ),
                (
                    "value_soft_rock",
                    models.FloatField(blank=True, null=True, verbose_name="연암(분/m)"),
                ),
                (
                    "value_hard_rock",
                    models.FloatField(blank=True, null=True, verbose_name="경암(분/m)"),
                ),
                (
                    "value_mixed",
                    models.FloatField(blank=True, null=True, verbose_name="혼합층(분/m)"),
                ),
            ],
            options={
                "verbose_name": "기성말뚝 기준",
                "verbose_name_plural": "기성말뚝 기준 목록",
                "unique_together": {("pile_type", "diameter_spec")},
            },
        ),
    ]
