# Generated by Django 5.2.5 on 2026-01-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConstructionProductivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main_category", models.CharField(max_length=100, verbose_name="구분")),
                ("category", models.CharField(max_length=100, verbose_name="공종")),
                ("item_name", models.CharField(max_length=255, verbose_name="목차")),
                ("unit", models.CharField(max_length=50, verbose_name="단위")),
                ("crew_composition_text", models.TextField(verbose_name="산출근거(작업조)")),
                (
                    "productivity_type",
                    models.CharField(max_length=50, verbose_name="생산성 기준"),
                ),
                (
                    "skill_worker_1_pum",
                    models.FloatField(default=0.0, verbose_name="기능공1 품"),
                ),
                (
                    "skill_worker_1_count",
                    models.FloatField(default=0.0, verbose_name="기능공1 인원"),
                ),
                (
                    "skill_worker_2_pum",
                    models.FloatField(default=0.0, verbose_name="기능공2 품"),
                ),
                (
                    "skill_worker_2_count",
                    models.FloatField(default=0.0, verbose_name="기능공2 인원"),
                ),
                (
                    "special_worker_pum",
                    models.FloatField(default=0.0, verbose_name="특별인부 품"),
                ),
                (
                    "special_worker_count",
                    models.FloatField(default=0.0, verbose_name="특별인부 인원"),
                ),
                (
                    "common_worker_pum",
                    models.FloatField(default=0.0, verbose_name="보통인부 품"),
                ),
                (
                    "common_worker_count",
                    models.FloatField(default=0.0, verbose_name="보통인부 인원"),
                ),
                ("equipment_pum", models.FloatField(default=0.0, verbose_name="장비 품")),
                (
                    "equipment_count",
                    models.FloatField(default=0.0, verbose_name="장비 대수"),
                ),
                (
                    "pumsam_workload",
                    models.FloatField(default=0.0, verbose_name="표준품셈"),
                ),
                (
                    "molit_workload",
                    models.FloatField(default=0.0, verbose_name="국토부 가이드라인"),
                ),
            ],
            options={
                "verbose_name": "표준 생산성 데이터",
            },
        ),
    ]
