# Generated by Django 5.2.5 on 2026-01-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionproductivity",
            name="sub_category",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="세부공종"
            ),
        ),
    ]
