# Generated by Django 4.2.23 on 2026-02-20 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cpe_all_module", "0001_initial"),
        ("cpe_module", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pileresult",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pile_results",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pile_productivity_basis",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AddField(
            model_name="constructionscheduleitem",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_items",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AddField(
            model_name="constructionproductivity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="construction_productivities",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cip_results",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cip_productivity_bases",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AddField(
            model_name="boredpileresult",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bored_pile_results",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AddField(
            model_name="boredpileproductivitybasis",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bored_pile_productivity_bases",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
    ]
