# Generated by Django 5.2.5 on 2026-01-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0002_constructionproductivity_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionproductivity",
            name="item_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="목차"),
        ),
    ]
