# Generated by Django 5.2.5 on 2026-01-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0003_alter_constructionproductivity_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionproductivity",
            name="standard",
            field=models.CharField(blank=True, max_length=255, verbose_name="규격"),
        ),
    ]
