# Generated by Django 5.2.5 on 2026-01-12 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0004_constructionproductivity_standard"),
        ("cpe_module", "0010_project_calc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionproductivity",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="construction_productivities",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
    ]
