# Generated by Django 5.2.5 on 2026-01-12 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0005_constructionproductivity_project"),
        ("cpe_module", "0010_project_calc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIPProductivityBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="비고/설명")),
                (
                    "drill_diameter",
                    models.FloatField(default=0.0, verbose_name="천공 직경(mm)"),
                ),
                (
                    "total_depth",
                    models.FloatField(default=0.0, verbose_name="전체 깊이(m)"),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(default=0.0, verbose_name="점질토 깊이"),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(default=0.0, verbose_name="사질토 깊이"),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(default=0.0, verbose_name="풍화암 깊이"),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(default=0.0, verbose_name="연암 깊이"),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(default=0.0, verbose_name="경암 깊이"),
                ),
                (
                    "layer_depth_mixed",
                    models.FloatField(default=0.0, verbose_name="혼합층 깊이"),
                ),
                (
                    "t1_prepare",
                    models.FloatField(default=0.0, verbose_name="유도관 설치 및 해체(t1)"),
                ),
                (
                    "t2_drill_total",
                    models.FloatField(default=0.0, verbose_name="천공 시간 합계(t2)"),
                ),
                (
                    "t3_rebar",
                    models.FloatField(default=0.0, verbose_name="철근망 및 H형강 건입(t3)"),
                ),
                (
                    "t4_concrete",
                    models.FloatField(default=0.0, verbose_name="콘크리트 타설(t4)"),
                ),
                (
                    "classification_factor",
                    models.FloatField(default=0.8, verbose_name="작업계수(f)"),
                ),
                (
                    "cycle_time_per_hole",
                    models.FloatField(default=0.0, verbose_name="본당 사이클 타임(T)"),
                ),
                (
                    "daily_production_count",
                    models.FloatField(default=0.0, verbose_name="일일 작업량(공)"),
                ),
                (
                    "daily_production_meter",
                    models.FloatField(default=0.0, verbose_name="일일 작업량(m)"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cip_productivity_bases",
                        to="cpe_module.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "CIP 생산성 근거",
                "verbose_name_plural": "CIP 생산성 근거 목록",
            },
        ),
    ]
