# Generated by Django 5.2.5 on 2026-01-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0006_cipproductivitybasis"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIPDrillingStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bit_type",
                    models.CharField(
                        choices=[
                            ("AUGER", "오거비트"),
                            ("IMPROVED", "개량형비트"),
                            ("HAMMER", "해머비트"),
                        ],
                        max_length=20,
                        verbose_name="비트 타입",
                    ),
                ),
                (
                    "diameter_spec",
                    models.CharField(
                        help_text="예: 500미만, 500이상, 500~600",
                        max_length=50,
                        verbose_name="말뚝직경 규격",
                    ),
                ),
                (
                    "value_clay",
                    models.FloatField(blank=True, null=True, verbose_name="점질토"),
                ),
                (
                    "value_sand",
                    models.FloatField(blank=True, null=True, verbose_name="사질토"),
                ),
                (
                    "value_weathered",
                    models.FloatField(blank=True, null=True, verbose_name="풍화암"),
                ),
                (
                    "value_soft_rock",
                    models.FloatField(blank=True, null=True, verbose_name="연암"),
                ),
                (
                    "value_hard_rock",
                    models.FloatField(blank=True, null=True, verbose_name="경암"),
                ),
                (
                    "value_mixed",
                    models.FloatField(blank=True, null=True, verbose_name="혼합층"),
                ),
            ],
            options={
                "verbose_name": "CIP 천공 기준(표준품셈)",
                "verbose_name_plural": "CIP 천공 기준 목록",
            },
        ),
    ]
