# Generated by Django 5.2.5 on 2026-01-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0007_cipdrillingstandard"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cipproductivitybasis",
            old_name="t3_rebar",
            new_name="t3",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="cycle_time_per_hole",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="daily_production_meter",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="t1_prepare",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="t2_drill_total",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="t4_concrete",
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="bit_type",
            field=models.CharField(
                choices=[("AUGER", "오거비트"), ("IMPROVED", "개량형비트"), ("HAMMER", "해머비트")],
                default="AUGER",
                max_length=20,
                verbose_name="비트 타입",
            ),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="calculation_formula",
            field=models.CharField(blank=True, max_length=255, verbose_name="계산식"),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="concrete_pouring_length",
            field=models.FloatField(default=0.0, verbose_name="콘크리트 타설 길이(m)"),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="cycle_time",
            field=models.FloatField(default=0.0, verbose_name="본당 소요시간(T)"),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="t1",
            field=models.FloatField(default=0.0, verbose_name="준비시간(t1)"),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="t2",
            field=models.FloatField(default=0.0, verbose_name="천공시간(t2)"),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="t4",
            field=models.FloatField(default=0.0, verbose_name="콘크리트 타설 시간(t4)"),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="classification_factor",
            field=models.FloatField(default=1.0, verbose_name="작업계수(f)"),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="total_depth",
            field=models.FloatField(default=0.0, verbose_name="굴착 깊이 합계(m)"),
        ),
    ]
