# Generated by Django 5.2.5 on 2026-01-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0008_rename_t3_rebar_cipproductivitybasis_t3_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="bit_type",
        ),
    ]
