# Generated by Django 5.2.5 on 2026-01-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0009_remove_cipproductivitybasis_bit_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="calculation_formula",
            field=models.CharField(
                blank=True, help_text="참고용", max_length=255, verbose_name="계산식"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="classification_factor",
            field=models.FloatField(
                default=0.8, help_text="입력값", verbose_name="작업계수(f)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="concrete_pouring_length",
            field=models.FloatField(
                default=0.0, help_text="입력값 (m)", verbose_name="콘크리트 타설 길이(m)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="cycle_time",
            field=models.FloatField(
                default=0.0, help_text="계산값 (t1+t2+t3+t4)", verbose_name="본당 소요시간(T)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="daily_production_count",
            field=models.FloatField(
                default=0.0, help_text="계산값 (480*f/T)", verbose_name="일일 작업량(공)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="drill_diameter",
            field=models.FloatField(
                default=0.0, help_text="입력값", verbose_name="천공 직경(mm)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="layer_depth_clay",
            field=models.FloatField(
                default=0.0, help_text="입력값 (m)", verbose_name="점질토 깊이"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="layer_depth_hard_rock",
            field=models.FloatField(
                default=0.0, help_text="입력값 (m)", verbose_name="경암 깊이"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="layer_depth_mixed",
            field=models.FloatField(
                default=0.0, help_text="입력값 (m)", verbose_name="혼합층 깊이"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="layer_depth_sand",
            field=models.FloatField(
                default=0.0, help_text="입력값 (m)", verbose_name="사질토 깊이"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="layer_depth_soft_rock",
            field=models.FloatField(
                default=0.0, help_text="입력값 (m)", verbose_name="연암 깊이"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="layer_depth_weathered",
            field=models.FloatField(
                default=0.0, help_text="입력값 (m)", verbose_name="풍화암 깊이"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="t1",
            field=models.FloatField(
                default=3.0, help_text="입력값 (분)", verbose_name="준비시간(t1)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="t2",
            field=models.FloatField(
                default=0.0, help_text="계산값 (지층별 깊이 * 굴착속도)", verbose_name="천공시간(t2)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="t3",
            field=models.FloatField(
                default=2.0, help_text="입력값 (분)", verbose_name="철근망 및 H형강 건입(t3)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="t4",
            field=models.FloatField(
                default=0.0, help_text="계산값 (타설 길이 기반)", verbose_name="콘크리트 타설 시간(t4)"
            ),
        ),
        migrations.AlterField(
            model_name="cipproductivitybasis",
            name="total_depth",
            field=models.FloatField(
                default=0.0, help_text="계산값 (지층 깊이 합계)", verbose_name="굴착 깊이 합계(m)"
            ),
        ),
    ]
