# Generated by Django 5.2.5 on 2026-01-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cpe_all_module",
            "0010_alter_cipproductivitybasis_calculation_formula_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="bit_type_clay",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="점질토 비트"
            ),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="bit_type_hard_rock",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="경암 비트"
            ),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="bit_type_mixed",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="혼합층 비트"
            ),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="bit_type_sand",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="사질토 비트"
            ),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="bit_type_soft_rock",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="연암 비트"
            ),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="bit_type_weathered",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="풍화암 비트"
            ),
        ),
        migrations.AddField(
            model_name="cipproductivitybasis",
            name="diameter_selection",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="직경 규격(선택)"
            ),
        ),
    ]
