# Generated by Django 5.2.5 on 2026-01-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0011_cipproductivitybasis_bit_type_clay_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="bit_type_clay",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="bit_type_hard_rock",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="bit_type_mixed",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="bit_type_sand",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="bit_type_soft_rock",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="bit_type_weathered",
        ),
        migrations.RemoveField(
            model_name="cipproductivitybasis",
            name="diameter_selection",
        ),
    ]
