# Generated by Django 5.2.5 on 2026-01-13 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0012_remove_cipproductivitybasis_bit_type_clay_and_more"),
        ("cpe_module", "0010_project_calc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="CIPResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diameter_selection",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="직경 규격(선택)"
                    ),
                ),
                (
                    "bit_type_clay",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="점질토 비트"
                    ),
                ),
                (
                    "bit_type_sand",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="사질토 비트"
                    ),
                ),
                (
                    "bit_type_weathered",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="풍화암 비트"
                    ),
                ),
                (
                    "bit_type_soft_rock",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="연암 비트"
                    ),
                ),
                (
                    "bit_type_hard_rock",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="경암 비트"
                    ),
                ),
                (
                    "bit_type_mixed",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="혼합층 비트"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cip_results",
                        to="cpe_module.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
        ),
    ]
