# Generated by Django 5.2.5 on 2026-01-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0013_cipresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="cipresult",
            name="cycle_time",
            field=models.FloatField(default=0.0, verbose_name="본당 작업시간(분)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="daily_production_count",
            field=models.FloatField(default=0.0, verbose_name="일일 생산성(본)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="layer_depth_clay",
            field=models.FloatField(default=0.0, verbose_name="점질토 깊이(m)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="layer_depth_hard_rock",
            field=models.FloatField(default=0.0, verbose_name="경암 깊이(m)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="layer_depth_mixed",
            field=models.FloatField(default=0.0, verbose_name="혼합층 깊이(m)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="layer_depth_sand",
            field=models.FloatField(default=0.0, verbose_name="사질토 깊이(m)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="layer_depth_soft_rock",
            field=models.FloatField(default=0.0, verbose_name="연암 깊이(m)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="layer_depth_weathered",
            field=models.FloatField(default=0.0, verbose_name="풍화암 깊이(m)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="t2",
            field=models.FloatField(default=0.0, verbose_name="천공 시간(t2, 분)"),
        ),
        migrations.AddField(
            model_name="cipresult",
            name="total_depth",
            field=models.FloatField(default=0.0, verbose_name="합계 깊이(m)"),
        ),
    ]
