# Generated by Django 5.2.5 on 2026-01-13 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0014_cipresult_cycle_time_and_more"),
        ("cpe_module", "0010_project_calc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PileProductivityBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="설명"),
                ),
                (
                    "pile_diameter",
                    models.FloatField(default=0.0, verbose_name="말뚝직경(mm)"),
                ),
                ("pile_length", models.FloatField(default=0.0, verbose_name="말뚝길이(m)")),
                (
                    "layer_depth_clay",
                    models.FloatField(default=0.0, verbose_name="점질토 깊이(m)"),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(default=0.0, verbose_name="사질토 깊이(m)"),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(default=0.0, verbose_name="풍화암 깊이(m)"),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(default=0.0, verbose_name="연암 깊이(m)"),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(default=0.0, verbose_name="경암 깊이(m)"),
                ),
                (
                    "layer_depth_mixed",
                    models.FloatField(default=0.0, verbose_name="혼합층 깊이(m)"),
                ),
                (
                    "total_depth",
                    models.FloatField(default=0.0, verbose_name="굴착 깊이 합계(m)"),
                ),
                ("t2", models.FloatField(default=0.0, verbose_name="항타 시간(t2)")),
                ("weld_time", models.FloatField(default=0.0, verbose_name="용접 시간")),
                (
                    "cycle_time",
                    models.FloatField(default=0.0, verbose_name="본당 소요시간(T)"),
                ),
                (
                    "daily_production_count",
                    models.FloatField(default=0.0, verbose_name="일일 작업량(공)"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pile_productivity_basis",
                        to="cpe_module.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "기성말뚝 생산성 근거",
                "verbose_name_plural": "기성말뚝 생산성 근거 목록",
            },
        ),
        migrations.CreateModel(
            name="PileResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diameter_selection",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="직경 규격(선택)"
                    ),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(default=0.0, verbose_name="점질토 깊이(m)"),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(default=0.0, verbose_name="사질토 깊이(m)"),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(default=0.0, verbose_name="풍화암 깊이(m)"),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(default=0.0, verbose_name="연암 깊이(m)"),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(default=0.0, verbose_name="경암 깊이(m)"),
                ),
                (
                    "layer_depth_mixed",
                    models.FloatField(default=0.0, verbose_name="혼합층 깊이(m)"),
                ),
                (
                    "pile_type_clay",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="점질토 말뚝종류"
                    ),
                ),
                (
                    "pile_type_sand",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="사질토 말뚝종류"
                    ),
                ),
                (
                    "pile_type_weathered",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="풍화암 말뚝종류"
                    ),
                ),
                (
                    "pile_type_soft_rock",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="연암 말뚝종류"
                    ),
                ),
                (
                    "pile_type_hard_rock",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="경암 말뚝종류"
                    ),
                ),
                (
                    "pile_type_mixed",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="혼합층 말뚝종류"
                    ),
                ),
                (
                    "total_depth",
                    models.FloatField(default=0.0, verbose_name="합계 깊이(m)"),
                ),
                ("t2", models.FloatField(default=0.0, verbose_name="항타 시간(t2, 분)")),
                ("weld_time", models.FloatField(default=0.0, verbose_name="용접 시간(분)")),
                (
                    "cycle_time",
                    models.FloatField(default=0.0, verbose_name="본당 작업시간(분)"),
                ),
                (
                    "daily_production_count",
                    models.FloatField(default=0.0, verbose_name="일일 생산성(본)"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pile_results",
                        to="cpe_module.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "기성말뚝 결과",
                "verbose_name_plural": "기성말뚝 결과 목록",
            },
        ),
        migrations.CreateModel(
            name="PileStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pile_type",
                    models.CharField(
                        choices=[
                            ("PHC", "PHC 말뚝"),
                            ("STEEL", "강관 말뚝"),
                            ("COMPOSITE", "합성 말뚝"),
                        ],
                        max_length=20,
                        verbose_name="말뚝 종류",
                    ),
                ),
                (
                    "diameter_spec",
                    models.CharField(max_length=50, verbose_name="직경 규격"),
                ),
                (
                    "value_clay",
                    models.FloatField(blank=True, null=True, verbose_name="점질토(분/m)"),
                ),
                (
                    "value_sand",
                    models.FloatField(blank=True, null=True, verbose_name="사질토(분/m)"),
                ),
                (
                    "value_weathered",
                    models.FloatField(blank=True, null=True, verbose_name="풍화암(분/m)"),
                ),
                (
                    "value_soft_rock",
                    models.FloatField(blank=True, null=True, verbose_name="연암(분/m)"),
                ),
                (
                    "value_hard_rock",
                    models.FloatField(blank=True, null=True, verbose_name="경암(분/m)"),
                ),
                (
                    "value_mixed",
                    models.FloatField(blank=True, null=True, verbose_name="혼합층(분/m)"),
                ),
            ],
            options={
                "verbose_name": "기성말뚝 기준",
                "verbose_name_plural": "기성말뚝 기준 목록",
                "unique_together": {("pile_type", "diameter_spec")},
            },
        ),
    ]
