# Generated by Django 5.2.5 on 2026-01-13 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0015_pileproductivitybasis_pileresult_pilestandard"),
        ("cpe_module", "0010_project_calc_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pileproductivitybasis",
            name="pile_length",
        ),
        migrations.RemoveField(
            model_name="pileproductivitybasis",
            name="weld_time",
        ),
        migrations.RemoveField(
            model_name="pileresult",
            name="weld_time",
        ),
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="calculation_formula",
            field=models.CharField(blank=True, max_length=255, verbose_name="계산식"),
        ),
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="classification_factor",
            field=models.FloatField(default=0.85, verbose_name="작업계수(f)"),
        ),
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="grouting_length",
            field=models.FloatField(default=0.0, verbose_name="그라우팅 길이(m)"),
        ),
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="t1",
            field=models.FloatField(default=5.0, verbose_name="준비시간(t1, 분)"),
        ),
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="t3",
            field=models.FloatField(default=8.0, verbose_name="말뚝 근입/항타(t3, 분)"),
        ),
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="t4",
            field=models.FloatField(default=0.0, verbose_name="그라우팅(t4, 분)"),
        ),
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="t5",
            field=models.FloatField(default=18.0, verbose_name="용접(t5, 분)"),
        ),
        migrations.AddField(
            model_name="pileresult",
            name="classification_factor",
            field=models.FloatField(default=0.85, verbose_name="작업계수(f)"),
        ),
        migrations.AddField(
            model_name="pileresult",
            name="grouting_length",
            field=models.FloatField(default=0.0, verbose_name="그라우팅 길이(m)"),
        ),
        migrations.AddField(
            model_name="pileresult",
            name="t1",
            field=models.FloatField(default=5.0, verbose_name="준비시간(t1, 분)"),
        ),
        migrations.AddField(
            model_name="pileresult",
            name="t3",
            field=models.FloatField(default=8.0, verbose_name="말뚝 근입/항타(t3, 분)"),
        ),
        migrations.AddField(
            model_name="pileresult",
            name="t4",
            field=models.FloatField(default=0.0, verbose_name="그라우팅(t4, 분)"),
        ),
        migrations.AddField(
            model_name="pileresult",
            name="t5",
            field=models.FloatField(default=18.0, verbose_name="용접(t5, 분)"),
        ),
        migrations.AlterField(
            model_name="pileproductivitybasis",
            name="cycle_time",
            field=models.FloatField(default=0.0, verbose_name="본당 소요시간(T, 분)"),
        ),
        migrations.AlterField(
            model_name="pileproductivitybasis",
            name="daily_production_count",
            field=models.FloatField(default=0.0, verbose_name="일일 작업량(본)"),
        ),
        migrations.AlterField(
            model_name="pileproductivitybasis",
            name="pile_diameter",
            field=models.FloatField(default=500.0, verbose_name="말뚝직경(mm)"),
        ),
        migrations.AlterField(
            model_name="pileproductivitybasis",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pile_productivity_basis",
                to="cpe_module.project",
                verbose_name="프로젝트",
            ),
        ),
        migrations.AlterField(
            model_name="pileproductivitybasis",
            name="t2",
            field=models.FloatField(default=0.0, verbose_name="항타 시간(t2, 분)"),
        ),
    ]
