# Generated by Django 5.2.5 on 2026-01-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0016_remove_pileproductivitybasis_pile_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilestandard",
            name="pile_type",
            field=models.CharField(
                choices=[("AUGER", "오거비트"), ("IMPROVED", "개량형비트"), ("HAMMER", "해머비트")],
                max_length=20,
                verbose_name="말뚝 종류",
            ),
        ),
    ]
