# Generated by Django 5.2.5 on 2026-01-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0017_alter_pilestandard_pile_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pileproductivitybasis",
            name="welding_diameter",
            field=models.FloatField(default=500.0, verbose_name="용접 직경(mm)"),
        ),
        migrations.AddField(
            model_name="pileresult",
            name="welding_diameter",
            field=models.FloatField(default=500.0, verbose_name="용접 직경(mm)"),
        ),
    ]
