# Generated by Django 5.2.5 on 2026-01-13 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0018_pileproductivitybasis_welding_diameter_and_more"),
        ("cpe_module", "0010_project_calc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BoredPileStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("RCD", "R.C.D"),
                            ("OSCILLATOR", "요동식"),
                            ("ALL_CASING", "전회전식"),
                        ],
                        max_length=20,
                        verbose_name="공법",
                    ),
                ),
                (
                    "diameter_spec",
                    models.CharField(
                        help_text="예: 1000, 1500, 2000, 2500, 3000",
                        max_length=50,
                        verbose_name="말뚝직경 규격",
                    ),
                ),
                (
                    "value_clay",
                    models.FloatField(blank=True, null=True, verbose_name="점질토"),
                ),
                (
                    "value_sand",
                    models.FloatField(blank=True, null=True, verbose_name="사질토"),
                ),
                (
                    "value_gravel",
                    models.FloatField(blank=True, null=True, verbose_name="자갈"),
                ),
                (
                    "value_weathered",
                    models.FloatField(blank=True, null=True, verbose_name="풍화암"),
                ),
                (
                    "value_soft_rock",
                    models.FloatField(blank=True, null=True, verbose_name="연암"),
                ),
                (
                    "value_hard_rock",
                    models.FloatField(blank=True, null=True, verbose_name="경암"),
                ),
            ],
            options={
                "verbose_name": "현장타설말뚝 천공 기준",
                "verbose_name_plural": "현장타설말뚝 천공 기준 목록",
            },
        ),
        migrations.CreateModel(
            name="BoredPileProductivityBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="비고/설명")),
                (
                    "t1",
                    models.FloatField(
                        default=2.0, help_text="입력값 (시간)", verbose_name="준비시간(t1)"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="굴착 공법"
                    ),
                ),
                (
                    "pile_diameter",
                    models.FloatField(
                        default=0.0, help_text="입력값", verbose_name="말뚝 직경(mm)"
                    ),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="점질토 깊이"
                    ),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="사질토 깊이"
                    ),
                ),
                (
                    "layer_depth_gravel",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="자갈 깊이"
                    ),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="풍화암 깊이"
                    ),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="연암 깊이"
                    ),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(
                        default=0.0, help_text="입력값 (m)", verbose_name="경암 깊이"
                    ),
                ),
                (
                    "classification_factor",
                    models.FloatField(
                        default=0.85, help_text="입력값", verbose_name="작업계수(f)"
                    ),
                ),
                (
                    "total_depth",
                    models.FloatField(
                        default=0.0, help_text="계산값", verbose_name="굴착 깊이 합계(m)"
                    ),
                ),
                (
                    "t2",
                    models.FloatField(
                        default=0.0, help_text="계산값 (시간)", verbose_name="천공시간(t2)"
                    ),
                ),
                (
                    "cycle_time",
                    models.FloatField(
                        default=0.0, help_text="계산값 (시간)", verbose_name="본당 소요시간(T)"
                    ),
                ),
                (
                    "daily_production_count",
                    models.FloatField(
                        default=0.0, help_text="계산값 (8/T)", verbose_name="일일 작업량(본)"
                    ),
                ),
                (
                    "calculation_formula",
                    models.CharField(
                        blank=True, help_text="참고용", max_length=255, verbose_name="계산식"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bored_pile_productivity_bases",
                        to="cpe_module.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "현장타설말뚝 생산성 근거",
                "verbose_name_plural": "현장타설말뚝 생산성 근거 목록",
            },
        ),
        migrations.CreateModel(
            name="BoredPileResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_selection",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="공법 선택"
                    ),
                ),
                (
                    "diameter_selection",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="직경 규격(선택)"
                    ),
                ),
                (
                    "layer_depth_clay",
                    models.FloatField(default=0.0, verbose_name="점질토 깊이(m)"),
                ),
                (
                    "layer_depth_sand",
                    models.FloatField(default=0.0, verbose_name="사질토 깊이(m)"),
                ),
                (
                    "layer_depth_gravel",
                    models.FloatField(default=0.0, verbose_name="자갈 깊이(m)"),
                ),
                (
                    "layer_depth_weathered",
                    models.FloatField(default=0.0, verbose_name="풍화암 깊이(m)"),
                ),
                (
                    "layer_depth_soft_rock",
                    models.FloatField(default=0.0, verbose_name="연암 깊이(m)"),
                ),
                (
                    "layer_depth_hard_rock",
                    models.FloatField(default=0.0, verbose_name="경암 깊이(m)"),
                ),
                ("t1", models.FloatField(default=2.0, verbose_name="준비시간(t1, 시간)")),
                (
                    "classification_factor",
                    models.FloatField(default=0.85, verbose_name="작업계수(f)"),
                ),
                (
                    "total_depth",
                    models.FloatField(default=0.0, verbose_name="합계 깊이(m)"),
                ),
                ("t2", models.FloatField(default=0.0, verbose_name="천공 시간(t2, 시간)")),
                (
                    "cycle_time",
                    models.FloatField(default=0.0, verbose_name="본당 작업시간(시간)"),
                ),
                (
                    "daily_production_count",
                    models.FloatField(default=0.0, verbose_name="일일 생산성(본)"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bored_pile_results",
                        to="cpe_module.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "현장타설말뚝 결과 요약",
                "verbose_name_plural": "현장타설말뚝 결과 요약 목록",
            },
        ),
    ]
