# Generated by Django 5.2.5 on 2026-01-13 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cpe_all_module",
            "0019_boredpilestandard_boredpileproductivitybasis_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="boredpileresult",
            name="method_clay",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="점질토 공법"
            ),
        ),
        migrations.AddField(
            model_name="boredpileresult",
            name="method_gravel",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="자갈 공법"
            ),
        ),
        migrations.AddField(
            model_name="boredpileresult",
            name="method_hard_rock",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="경암 공법"
            ),
        ),
        migrations.AddField(
            model_name="boredpileresult",
            name="method_sand",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="사질토 공법"
            ),
        ),
        migrations.AddField(
            model_name="boredpileresult",
            name="method_soft_rock",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="연암 공법"
            ),
        ),
        migrations.AddField(
            model_name="boredpileresult",
            name="method_weathered",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="풍화암 공법"
            ),
        ),
    ]
