# Generated by Django 5.2.5 on 2026-01-13 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0020_boredpileresult_method_clay_and_more"),
        ("cpe_module", "0010_project_calc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructionScheduleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="정렬 순서")),
                (
                    "main_category",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="구분 (Level 1)"
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="공정 (Level 2)"
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="공종 (Level 3)"
                    ),
                ),
                (
                    "quantity_formula",
                    models.TextField(blank=True, verbose_name="수량산출식"),
                ),
                (
                    "unit",
                    models.CharField(blank=True, max_length=50, verbose_name="단위"),
                ),
                ("quantity", models.FloatField(default=0.0, verbose_name="수량")),
                ("productivity", models.FloatField(default=0.0, verbose_name="생산성")),
                ("crew_size", models.FloatField(default=1.0, verbose_name="투입조")),
                (
                    "daily_production",
                    models.FloatField(default=0.0, verbose_name="1일 생산량"),
                ),
                (
                    "working_days",
                    models.FloatField(default=0.0, verbose_name="작업기간 (W.D)"),
                ),
                (
                    "operating_rate_type",
                    models.CharField(blank=True, max_length=50, verbose_name="가동률 종류"),
                ),
                (
                    "operating_rate_value",
                    models.FloatField(default=1.0, verbose_name="가동률 (%)"),
                ),
                (
                    "calendar_days",
                    models.FloatField(default=0.0, verbose_name="소요일 (Calendar Day)"),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="비고")),
                (
                    "standard_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="표준품셈 코드"
                    ),
                ),
                (
                    "link_module_type",
                    models.CharField(
                        choices=[
                            ("CIP", "CIP"),
                            ("PILE", "PILE"),
                            ("BORED_PILE", "Bored Pile"),
                            ("NONE", "None"),
                        ],
                        default="NONE",
                        max_length=20,
                        verbose_name="연동 모듈",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cpe_all_module.constructionscheduleitem",
                        verbose_name="상위 항목",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="cpe_module.project",
                        verbose_name="프로젝트",
                    ),
                ),
            ],
            options={
                "verbose_name": "공기산정 상세 항목",
                "ordering": ["order", "id"],
            },
        ),
    ]
