# Generated by Django 5.2.5 on 2026-01-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpe_all_module", "0021_constructionscheduleitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="constructionscheduleitem",
            options={"verbose_name": "공기산정 상세 항목 (JSON)"},
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="calendar_days",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="crew_size",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="daily_production",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="link_module_type",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="main_category",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="operating_rate_type",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="operating_rate_value",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="order",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="process",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="productivity",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="quantity_formula",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="standard_code",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="unit",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="work_type",
        ),
        migrations.RemoveField(
            model_name="constructionscheduleitem",
            name="working_days",
        ),
        migrations.AddField(
            model_name="constructionscheduleitem",
            name="data",
            field=models.JSONField(
                blank=True, default=list, verbose_name="스케줄 데이터 (JSON)"
            ),
        ),
    ]
